distribution/pull_v2_windows.go

When a manifest list contains both Linux and Windows images, always
prefer Windows when the platform OS is unspecified. Also, filter out any
Windows images with a higher build than the host, since they cannot run.
cherry picked from commit ddcdb7255d960a4b2049439245a4f887b26af891 (https://github.com/moby/moby/pull/37369) - no conflicts

[18.06] LCOW: Prefer Windows over Linux in a manifest list

---

vendor.conf
vendor/github.com/docker/swarmkit/api/objects.pb.go
vendor/github.com/docker/swarmkit/api/storeobject.go
vendor/github.com/docker/swarmkit/manager/dispatcher/dispatcher.go
vendor/github.com/docker/swarmkit/manager/metrics/collector.go
vendor/github.com/docker/swarmkit/manager/orchestrator/taskreaper/task_reaper.go

cherry-pick of https://github.com/moby/moby/pull/37399 for 18.06. cherry pick was clean, no conflicts
This includes the following behavior-modifying PRs:
- docker/swarmkit#2673
- docker/swarmkit#2669
- docker/swarmkit#2675
- docker/swarmkit#2664

[18.06] Bump swarmkit to include task reaper fixes and more metrics.

---

api/server/router/build/build_routes.go
builder/builder-next/adapters/snapshot/snapshot.go

(cherry picked from commit ffa7233d1538363fe12ad609e720b8d75e8768de)
Signed-off-by: Tibor Vass <tibor@docker.com>
Clean cherry-pick from https://github.com/moby/moby/pull/37431

[18.06] builder: fix duplicate calls to mountable

---

daemon/logger/loggerutils/logfile.go

cherry-pick of https://github.com/moby/moby/pull/37412 for 18.06
fixes https://github.com/moby/moby/issues/30046 for 18.06
```
git checkout -b 18.06-backport-logissue ce-engine/18.06
git cherry-pick -s -S -x df84cdd091631f32abaedd805791db89ac5c83d4
```

[18.06] backport select polling based watcher for Windows log watcher

---

libcontainerd/supervisor/remote_daemon.go

backport:
* https://github.com/moby/moby/pull/37758 Fix supervisor healthcheck throttling
cherry pick https://github.com/moby/moby/pull/37758/commits/c3e3293 with no conflicts:
```
$ git cherry-pick -s -x c3e3293
[sup f121eccf29] Fix supervisor healthcheck throttling
Author: Derek McGowan <derek@mcgstyle.net>
Date: Tue Sep 4 11:00:28 2018 -0700
1 file changed, 35 insertions(+), 26 deletions(-)
```

[18.09] Fix supervisor healthcheck throttling

---

libcontainerd/supervisor/remote_daemon.go

backport of https://github.com/moby/moby/pull/37759 for 18.09;
```
git checkout -b 18.09_backport_fix-libcontainerd-startup-error ce-engine/18.09
git cherry-pick -s -S -x ce0b0b72bcc58de82ba1e0e7127499d07f678122
```
Prevents looping of startup errors such as containerd not being found on the path.

[18.09] backport: Add fail fast path when containerd fails on startup

---

vendor.conf
vendor/github.com/moby/buildkit/cache/contenthash/checksum.go
vendor/github.com/moby/buildkit/cache/contenthash/path.go
vendor/github.com/moby/buildkit/client/llb/state.go
vendor/github.com/moby/buildkit/executor/oci/spec_unix.go
vendor/github.com/moby/buildkit/executor/runcexecutor/executor.go
vendor/github.com/moby/buildkit/frontend/dockerfile/builder/build.go
vendor/github.com/moby/buildkit/frontend/dockerfile/dockerfile2llb/convert.go
vendor/github.com/moby/buildkit/frontend/gateway/client/client.go
vendor/github.com/moby/buildkit/frontend/gateway/forwarder/forward.go
vendor/github.com/moby/buildkit/frontend/gateway/grpcclient/client.go
vendor/github.com/moby/buildkit/solver/edge.go
vendor/github.com/moby/buildkit/solver/jobs.go

Signed-off-by: Tibor Vass <tibor@docker.com>
(cherry picked from commit e161a8d1e9e84f50410860d903205e6d2dc86110)
Signed-off-by: Tibor Vass <tibor@docker.com>
No conflicts

[18.09] vendor buildkit to 8f4dff0d16ea91cb43315d5f5aa4b27f4fe4e1f2

---

builder/builder-next/adapters/snapshot/snapshot.go

backport of https://github.com/moby/moby/pull/38067 for 18.09
```
git checkout -b 18.09_backport_fix-duplicate-release ce-engine/18.09
git cherry-pick -s -S -x 2732fe527f9258561c7310c128914b4b456c8404
```
A possible fix for https://github.com/moby/buildkit/issues/691
Follow up to the previous fix https://github.com/moby/moby/pull/37431
There is a condition (from the readonly mount sharing) where multiple calls can be made against `Mountable` so that the first one calls `Release()` after the second one has returned mounts but has not used them yet. I never managed to reproduce it myself but when I add a sleep to a specific line this becomes 100% reproducible. The error matches the https://github.com/moby/buildkit/issues/691 report.

[18.09 backport] builder: fix duplicate mount release

---

layer/layer_store.go

backport of https://github.com/moby/moby/pull/38413 for 18.09. Backport was clean; no conflicts
In applyTar, if the driver's ApplyDiff returns an error, the function
returns early without calling io.Copy.
As a consequence, the resources (a goroutine and some buffers holding
the uncompressed image, the digest, etc...) allocated or referenced by
NewInputTarStream above aren't released, as the worker goroutine only
finishes when it finds EOF or a closed pipe.
Signed-off-by: Sergio Lopez <slp@redhat.com>
(cherry picked from commit 5846db10af9fb37061ab92a07c3d82fbea92b2e0)

[18.09 backport] layer/layer_store: ensure NewInputTarStream resources are released

---

hack/dockerfile/install/proxy.installer
vendor.conf
vendor/github.com/docker/libnetwork/default_gateway.go
vendor/github.com/docker/libnetwork/iptables/iptables.go
vendor/github.com/docker/libnetwork/network.go
vendor/github.com/docker/libnetwork/networkdb/cluster.go

full diff: https://github.com/docker/libnetwork/compare/2cfbf9b1f98162a55829a21cc603c76072a75382...4725f2163fb214a6312f3beae5991f838ec36326
relevant changes:
- https://github.com/docker/libnetwork/pull/2344 (reverts https://github.com/docker/libnetwork/pull/2286 / https://github.com/docker/libnetwork/pull/2285)
- https://github.com/docker/libnetwork/pull/2327 Fix possible nil pointer exception

[18.09] bump libnetwork 4725f2163fb (bump_18.09 branch)

---

builder/remotecontext/git/gitutils.go
builder/remotecontext/git/gitutils_test.go

backport of https://github.com/moby/moby/pull/38944 for 18.09

[18.09 backport] gitutils: add validation for ref

---

vendor.conf
vendor/github.com/docker/swarmkit/manager/orchestrator/constraintenforcer/constraint_enforcer.go

Revendors docker/swarmkit to backport fixes made to the ConstraintEnforcer (see docker/swarmkit#2857)

[19.03 backport] ConstraintEnforcer fix

---

contrib/dockerd-rootless.sh
hack/dockerfile/install/rootlesskit.installer

Backport https://github.com/moby/moby/pull/39222

[19.03 backport] rootless: fix killing daemon

---

daemon/graphdriver/windows/windows.go

backport of https://github.com/moby/moby/pull/39320 for 19.03
A slightly more targeted than #39290 after debugging why RS1 CI has recently started failing with errors such as below:
```
PASS: docker_api_build_test.go:56: DockerSuite.TestBuildAPIRemoteTarballContext 0.006s
----------------------------------------------------------------------
FAIL: check_test.go:107: DockerSuite.TearDownTest
assertion failed: error is not nil: Error response from daemon: failed to detach VHD: invalid argument: rename D:\CI\CI-539e72f75b\daemon\windowsfilter\139a1ff3ca2768be069edab19e44fe65bd40e8d6fb21d582ab010bf1002b52c1 D:\CI\CI-539e72f75b\daemon\windowsfilter\139a1ff3ca2768be069edab19e44fe65bd40e8d6fb21d582ab010bf1002b52c1-removing: Access is denied.: failed to remove image …
```

[19.03 backport] Windows: Don't attempt detach VHD for R/O layers

---

container/container_unix.go
daemon/create_unix.go
daemon/create_windows.go
daemon/exec/exec.go
daemon/graphdriver/aufs/aufs_test.go
daemon/logger/plugin.go
daemon/names.go
integration-cli/docker_cli_external_volume_driver_unix_test.go
integration/container/rename_test.go
pkg/stringid/stringid.go
pkg/stringid/stringid_test.go
pkg/truncindex/truncindex_test.go
plugin/manager_linux_test.go
volume/mounts/linux_parser.go
volume/mounts/mounts.go
volume/mounts/windows_parser.go
volume/service/service.go

backport of https://github.com/moby/moby/pull/39336 for 19.03
Remove non cryptographic randomness.

[19.03 backport] Entropy cannot be saved

---

integration-cli/docker_cli_ps_test.go

backport of https://github.com/moby/moby/pull/39325 for 18.09 (see discussion on https://github.com/moby/moby/pull/39240)
This test runs on a daemon also used by other tests
so make sure we don't get failures if another test
doesn't cleanup or is running in parallel.

[18.09 backport] Harden TestPsListContainersFilterExited

---

daemon/graphdriver/windows/windows.go

backport of https://github.com/moby/moby/pull/39320 for 18.09
A slightly more targeted than #39290 after debugging why RS1 CI has recently started failing with errors such as below:
```
PASS: docker_api_build_test.go:56: DockerSuite.TestBuildAPIRemoteTarballContext 0.006s
----------------------------------------------------------------------
FAIL: check_test.go:107: DockerSuite.TearDownTest
assertion failed: error is not nil: Error response from daemon: failed to detach VHD: invalid argument: rename D:\CI\CI-539e72f75b\daemon\windowsfilter\139a1ff3ca2768be069edab19e44fe65bd40e8d6fb21d582ab010bf1002b52c1 D:\CI\CI-539e72f75b\daemon\windowsfilter\139a1ff3ca2768be069edab19e44fe65bd40e8d6fb21d582ab010bf1002b52c1-removing: Access is denied.: failed to remove image …
```

[18.09 backport] Windows: Don't attempt detach VHD for R/O layers

---

container/container_unix.go
daemon/create_unix.go
daemon/create_windows.go
daemon/exec/exec.go
daemon/graphdriver/aufs/aufs_test.go
daemon/logger/plugin.go
daemon/names.go
integration-cli/docker_cli_external_volume_driver_unix_test.go
integration/container/rename_test.go
pkg/stringid/stringid.go
pkg/stringid/stringid_test.go
pkg/truncindex/truncindex_test.go
plugin/manager_linux_test.go
volume/mounts/linux_parser.go
volume/mounts/mounts.go
volume/mounts/windows_parser.go
volume/service/service.go

backport of https://github.com/moby/moby/pull/39336 for 18.09
Remove non cryptographic randomness.

[18.09 backport] Entropy cannot be saved

---

daemon/daemon.go

backport of https://github.com/moby/moby/pull/38991 for 18.09
fixes https://github.com/moby/buildkit/issues/779 for 18.09

[18.09 backport] daemon: fix mirrors validation

---

integration/network/ipvlan/ipvlan_test.go

backport of https://github.com/moby/moby/pull/39358 for 19.03

[19.03 backport] For ipvlan tests check that the ipvlan module is enabled

---

daemon/logger/journald/journald.go
daemon/logger/journald/read.go

This is a backport of
* moby/moby#38859
* moby/moby#37819
Clean :cherries:-pick, no issues

[19.03] backport journald reading fixes (ENGCORE-941)

---

daemon/logger/journald/journald.go
daemon/logger/journald/read.go

This is a backport of
* moby/moby#38859
* moby/moby#37819
Clean :cherries:-pick, no issues

[18.09] backport journald reading fixes (ENGCORE-941)

---

vendor.conf
vendor/github.com/moby/buildkit/cache/remotecache/import.go
vendor/github.com/moby/buildkit/cache/remotecache/inline/inline.go
vendor/github.com/moby/buildkit/cache/remotecache/v1/utils.go
vendor/github.com/moby/buildkit/frontend/dockerfile/builder/build.go
vendor/github.com/moby/buildkit/frontend/dockerfile/dockerfile2llb/convert.go
vendor/github.com/moby/buildkit/frontend/dockerfile/dockerfile2llb/convert_runmount.go
vendor/github.com/moby/buildkit/solver/combinedcache.go
vendor/github.com/moby/buildkit/solver/jobs.go
vendor/github.com/moby/buildkit/solver/llbsolver/ops/exec.go
vendor/github.com/moby/buildkit/solver/pb/caps.go
vendor/github.com/moby/buildkit/source/git/gitsource.go

brings in https://github.com/moby/moby/pull/39745

[19.03] vendor: update buildkit to v0.6.1

---

builder/builder-next/adapters/snapshot/snapshot.go
builder/builder-next/exporter/export.go
vendor.conf
vendor/github.com/moby/buildkit/cache/contenthash/checksum.go
vendor/github.com/moby/buildkit/cache/refs.go
vendor/github.com/moby/buildkit/executor/oci/spec_unix.go
vendor/github.com/moby/buildkit/executor/runcexecutor/executor.go
vendor/github.com/moby/buildkit/snapshot/localmounter.go
vendor/github.com/moby/buildkit/snapshot/localmounter_unix.go
vendor/github.com/moby/buildkit/snapshot/localmounter_windows.go
vendor/github.com/moby/buildkit/snapshot/snapshotter.go
vendor/github.com/moby/buildkit/solver/llbsolver/file/refmanager.go
vendor/github.com/moby/buildkit/solver/llbsolver/ops/exec.go

- moby/moby#39782
- moby/moby#39781
Clean cherry-picks.

[19.03 backport] Cherry-picking build fixes

---

client/request.go

backport of https://github.com/moby/moby/pull/39588
addresses [DESKTOP-1286]
Improve the readability of the connection error displayed to the user on
Windows when running docker commands fails by checking if the client is
privileged. If so then display the actual error wrapped in a generic
error "This error may indicate that the docker daemon is not running."
If not that display the actual error wrapped in a more specific error:
"In the default daemon configuration on Windows, the docker client must
be run with elevated privileges to connect."
[DESKTOP-1286]: https://docker.atlassian.net/browse/DESKTOP-1286

[19.03 backport] Improve readability of Windows connect error

---

libcontainerd/remote/client.go

backport https://github.com/moby/moby/pull/39513
This prevents restarting event processing in a tight loop.
You can see this with the following steps:
```terminal
$ containerd &
$ dockerd --containerd=/run/containerd/containerd.sock &
$ pkill -9 containerd
```
At this point you will be spammed with logs such as:
```
ERRO[2019-07-12T22:29:37.318761400Z] failed to get event                           error="rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial unix /run/containerd/containerd.sock: connect: connection refused\"" module=libcontainerd namespace=plugins.moby
```
Without this change you can quickly end up with gigabytes of log data.

[19.03 backport] Sleep before restarting event processing

---

internal/test/daemon/daemon.go

backport of https://github.com/moby/moby/pull/39452 for 19.03
This improves the select logic for the restart tests or starting the
daemon in general.  With the way the ticker and select was setup, it was
possible for only the timeout to be displayed and not the wait errors.

[19.03 backport] Improve select for daemon restart tests

---

docs/rootless.md

backport of https://github.com/moby/moby/pull/40076

[19.03 backport] docs/rootless.md: update

---

integration-cli/docker_cli_start_test.go

The 19.03 branch has [failures](https://ci.docker.com/public/job/engine/job/19.03/60/execution/node/241/log/?consoleFull) on the tests run after PR merges:
```
--- FAIL: TestDockerSuite/TestStartReturnCorrectExitCode (9.39s)
docker_cli_start_test.go:198: assertion failed: 125 (exitCode int) != 12 (int): out: time="2019-10-30T18:28:20Z" level=error msg="error waiting for container: EOF" 
```
This PR is a clean backport of PR https://github.com/moby/moby/pull/40117

[19.03] Windows: disable flaky test TestStartReturnCorrectExitCode

---

vendor.conf
vendor/github.com/moby/buildkit/frontend/dockerfile/dockerfile2llb/convert.go
vendor/github.com/moby/buildkit/go.mod
vendor/github.com/moby/buildkit/solver/combinedcache.go
vendor/github.com/moby/buildkit/util/flightcontrol/flightcontrol.go
vendor/github.com/tonistiigi/fsutil/diff.go
vendor/github.com/tonistiigi/fsutil/diff_containerd.go
vendor/github.com/tonistiigi/fsutil/diskwriter.go
vendor/github.com/tonistiigi/fsutil/go.mod
vendor/github.com/tonistiigi/fsutil/receive.go
vendor/github.com/tonistiigi/fsutil/types/stat.go

https://github.com/moby/buildkit/compare/928f3b480d7460aacb401f68610058ffdb549aca...926935b590c94c3659ebcc49cf44da47c1a65ff6

[19.03] vendor: update buildkit to 926935b5

---

daemon/start.go

backport of https://github.com/moby/moby/pull/39828

[19.03 backport] daemon:containerStart() fix unhandled error for saveApparmorConfig

---

builder/builder-next/reqbodyhandler.go

backport of https://github.com/moby/moby/pull/39761
fixes https://github.com/moby/buildkit/issues/1138

[19.03 backport] builder-next: close build context upload on cancel
