api/server/backend/build/backend.go
api/server/router/build/build_routes.go
api/types/client.go
builder/builder-next/builder.go
builder/dockerfile/builder.go
builder/dockerfile/copy.go
builder/dockerfile/dispatchers.go
builder/dockerfile/dispatchers_test.go
builder/dockerfile/internals.go
client/image_build.go
pkg/streamformatter/streamformatter.go
pkg/streamformatter/streamformatter_test.go

Cherry-picks of:
- moby/moby#37368: builder: return image ID in API when using buildkit
- moby/moby#37381: api: Change Platform field back to string (temporary workaround)
(no conflicts)

[18.06] cherry-pick set for rc2

---

hack/dockerfile/install/containerd.installer

cherry-pick of https://github.com/moby/moby/pull/37357/commits/735517928b3c0a9dabdc087b1b2f366d72df3f4e (https://github.com/moby/moby/pull/37357) for 18.06
ping @dmcgowan @tonistiigi

[18.06] Update containerd to v1.1.1-rc.2

---

builder/builder-next/adapters/containerimage/pull.go
vendor.conf
vendor/github.com/moby/buildkit/README.md
vendor/github.com/moby/buildkit/cache/remotecache/export.go
vendor/github.com/moby/buildkit/executor/oci/user.go
vendor/github.com/moby/buildkit/executor/runcexecutor/executor.go
vendor/github.com/moby/buildkit/frontend/dockerfile/dockerfile2llb/convert.go
vendor/github.com/moby/buildkit/frontend/dockerfile/dockerfile2llb/convert_norunmount.go
vendor/github.com/moby/buildkit/frontend/dockerfile/dockerfile2llb/convert_runmount.go
vendor/github.com/moby/buildkit/frontend/dockerfile/instructions/bflag.go
vendor/github.com/moby/buildkit/frontend/dockerfile/instructions/commands.go
vendor/github.com/moby/buildkit/frontend/dockerfile/shell/equal_env_unix.go
vendor/github.com/moby/buildkit/frontend/dockerfile/shell/equal_env_windows.go
vendor/github.com/moby/buildkit/util/imageutil/config.go

cherry-pick of https://github.com/moby/moby/pull/37385 for 18.06; cherry-pick was clean, no conflicts
Brings in fixes for:
- https://github.com/moby/buildkit/issues/457 Stripped newlines in non-interactive (`--no-progress`) output
- https://github.com/moby/buildkit/issues/412 dockerfile: USER doesn't set additional group
- https://github.com/moby/buildkit/pull/484 pull: do not send duplicate status for completed jobs
- https://github.com/moby/buildkit/pull/470 Ensure BaseName of Stage is not blank
- relates to https://github.com/moby/moby/issues/37325
full diff: https://github.com/moby/buildkit/compare/cce2080ddbe4698912f2290892b247c83627efa8...9acf51e49185b348608e0096b2903dd72907adcb

[18.06] vendor: update buildkit to 9acf51e491

---

vendor.conf
vendor/github.com/Microsoft/go-winio/pipe.go

Fixes named pipe support for hyper-v isolated containers
cherry picked from commit 74095588baa0693a2c07bd05c001c42830f82ed3 (https://github.com/moby/moby/pull/37364) - no conflicts

[18.06] Update Microsoft/go-winio to 0.4.8

---

distribution/oci.go
distribution/registry.go

OCI types are backwards compatible with Docker manifest types, however the media types must be registered.
cherry picked from commit c4f0515837b834ec66ec463d92a32015062a0804 (https://github.com/moby/moby/pull/37359); no conflicts. cherry-pick was clean

[18.06] Register OCI image media types

---

oci/defaults.go

The deafult OCI linux spec in oci/defaults{_linux}.go in Docker/Moby
from 1.11 to current upstream master does not block /proc/acpi pathnames
allowing attackers to modify host's hardware like enabling/disabling
bluetooth or turning up/down keyboard brightness. SELinux prevents all
of this if enabled.
Fix for CVE-2018-10892
cherry-pick of https://github.com/moby/moby/pull/37404 for 18.06 (no conflicts)

[18.06] Add /proc/acpi to masked paths

---

daemon/volumes.go
volume/mounts/mounts.go

cherry-pick of https://github.com/moby/moby/pull/37378 for 18.06. cherry-pick was clean; no conflicts
When using the mounts API, bind mounts are not supposed to be
automatically created.
Before this patch there is a race condition between valiating that a
bind path exists and then actually setting up the bind mount where the
bind path may exist during validation but was removed during mountpooint
setup.
This adds a field to the mountpoint struct to ensure that binds created
over the mounts API are not accidentally created.

[18.06] Fix bindmount autocreate race

---

vendor.conf
vendor/github.com/docker/libnetwork/osl/namespace_linux.go
vendor/github.com/docker/libnetwork/vendor.conf

backport of https://github.com/moby/moby/pull/37424 for 18.06.
brings in:
- docker/libnetwork#2122 Changed loglevel from error to warning
-------------------
The absence of the file /proc/sys/net/ipv6/conf/all/disable_ipv6
doesn't appear to affect functionality, at least at this time.
(cherry picked from commit d58c4cbe6c781c78db352db2956e9949b8fc8609)

[18.06] Bump libnetwork to d00ceed44cc447c77f25cdf5d59e83163bdcb4c9

---

builder/dockerfile/dispatchers.go
builder/dockerfile/dispatchers_test.go
builder/dockerfile/internals.go

backport of https://github.com/moby/moby/pull/37413 for 18.06
```
git checkout -b 18.06-backport-do_not_Healthcheck_RUN_command ce-engine/18.06 
git cherry-pick -s -S -x 44e08d8a7d1249a1956018c6c3d3655642a4f273
```
Before this commit Healthcheck run if HEALTHCHECK
instruction appears before RUN instruction.
By passing `withoutHealthcheck` to `copyRunConfig`,
always RUN instruction run without Healthcheck.
Fix: https://github.com/moby/moby/issues/37362

[18.06] Ensure RUN instruction to run without Healthcheck

---

integration-cli/docker_cli_network_unix_test.go

cherry-pick of https://github.com/moby/moby/pull/37455 for 18.06
```
git checkout -b 18.06-backport-fix-internal ce-engine/18.06
git cherry-pick -s -S -x a2bb2144b3e0d49ac615976bfac462a307d85f0e
```
no conflicts, cherry-pick was clean
Instead of waiting for the DNS to fail, try to access
a specific external IP and verify that 100% of the pakcets
are being lost.

[18.06] Fix flakyness in TestDockerNetworkInternalMode

---

vendor.conf
vendor/github.com/docker/swarmkit/manager/dispatcher/dispatcher.go
vendor/github.com/docker/swarmkit/manager/scheduler/scheduler.go
vendor/github.com/docker/swarmkit/node/node.go

cherry-pick of https://github.com/moby/moby/pull/37484 for 18.06
```
git checkout -b 18.06-backport-bump_swarmkit ce-engine/18.06
git cherry-pick -s -S -x c9377f45529d5dce21c264947b73c7053f316467
```
full diff https://github.com/docker/swarmkit/compare/199cf49cd99690135d99e52a1907ec82e8113c4f...68266392a176434d282760d2d6d0ab4c68edcae6
- https://github.com/docker/swarmkit/pull/2706 address unassigned task leak when service is removed
- https://github.com/docker/swarmkit/pull/2676 Fix racy batching on the dispatcher 
- https://github.com/docker/swarmkit/pull/2693 Fix linting issues revealed by Go 1.11

[18.06] Update swarmkit to 68266392a176434d282760d2d6d0ab4c68edcae6

---

integration-cli/docker_cli_run_test.go

Cherry-pick of https://github.com/moby/moby/pull/37440 for 18.06
```
git checkout -b 18.06-backport-errorfix ce-engine/18.06
git cherry-pick -s -S -x 76ace9bb5e2c5ecdd02046956ab00f76c3b25a3a
```

[18.06] Fix error string in docker CLI test (Windows RS5)

---

integration/plugin/graphdriver/external_test.go

cherry-pick of https://github.com/moby/moby/pull/37477 for 18.06
```
git checkout -b 18.06-backport-fix_TestExternalGraphDriver_pull ce-engine/18.06
git cherry-pick -s -S -x 352db26d5fd896b681046b1119f07e0ce1ed45b8
```
This test occassionally fails on s390x and Power;
03:16:04 --- FAIL: TestExternalGraphDriver/pull (1.08s)
03:16:04 external_test.go:402: assertion failed: error is not nil: Error: No such image: busybox:latest
Most likely these failures are caused due to Docker Hub updating
the busybox:latest image, but not all architectures yet being
available.
Instead of using `:latest`, pull an image by digest, so that
the test doesn't depend on Docker Hub having all architectures
available for `:latest`.
I selected the same digest …

[18.06] Fix flaky TestExternalGraphDriver/pull test

---

cli/command/cli.go
cmd/dockerd/daemon.go
integration-cli/docker_cli_daemon_test.go
vendor.conf
vendor/github.com/docker/go-connections/tlsconfig/config.go

This is a cherry pick of the following 2 PRs:
- https://github.com/moby/moby/pull/33182
- https://github.com/moby/moby/pull/31977 (picked from the 17.04 one because the diff was smaller)
Cherry picks were not clean, but was a pretty easy resolution.
Unfortunately the test can't be merged - the test depends on features in go 1.8.x (`GetClientCertificate`), and 17.03 was on go 1.7.5.
Either I will have to try to figure out how to write a new test, or we leave it out.

[17.03] Patch go connections

---

integration-cli/docker_cli_daemon_test.go

Fixes some imports and a variable to be able to run test-integration-cli

[ce-17.03] Fix some test imports

---

libcontainerd/remote_daemon_linux.go

Implementation of https://github.com/moby/moby/pull/37519 fr 18.06, but without configuration option.
fixes https://github.com/moby/moby/issues/37507 for 18.06
Docker 18.06 does not have a configuration option to disable the CRI plugin, and this plugin is not very useful if containerd is not running standalone.
This patch disables the plugin if containerd is running as child-process of dockerd.
- build dockerd with this patch
- start the daemon (`dockerd &`)
- verify that the plugin is disabled in containerd's generated configuration file;
```
cat /var/run/docker/containerd/containerd.toml | grep disabled_plugins
disabled_plugins = ["cri"]
```
```
* Disable the containerd CRI plugin if containerd is running as child-process of …
```

[18.06] disable containerd CRI plugin

---

vendor.conf
vendor/github.com/docker/swarmkit/agent/agent.go
vendor/github.com/docker/swarmkit/agent/session.go
vendor/github.com/docker/swarmkit/ca/certificates.go
vendor/github.com/docker/swarmkit/manager/manager.go
vendor/github.com/docker/swarmkit/manager/orchestrator/task.go
vendor/github.com/docker/swarmkit/manager/orchestrator/taskreaper/task_reaper.go
vendor/github.com/docker/swarmkit/manager/state/raft/transport/peer.go
vendor/github.com/docker/swarmkit/vendor.conf

Backport of https://github.com/moby/moby/pull/37586 for 18.06
```
git checkout -b 18.06-bump_swarmkit ce-engine/18.06
git cherry-pick -s -S -x 660fa129c0ea09c1aa1770b5f2d26ec762213484
```
Full diff: https://github.com/docker/swarmkit/compare/68266392a176434d282760d2d6d0ab4c68edcae6...8852e8840e30d69db0b39a4a3d6447362e17c64f
Relevant changes;
- https://github.com/docker/swarmkit/pull/2593 agent: return error when failing to apply network key 
- https://github.com/docker/swarmkit/pull/2645 Replace deprecated grpc functions
- https://github.com/docker/swarmkit/pull/2720 Test if error is nil before to log it
- https://github.com/docker/swarmkit/pull/2712 [orchestrator] Fix task sorting
- addresses …

[18.06] Bump SwarmKit to 8852e88

---

builder/dockerfile/dispatchers.go
builder/dockerfile/dispatchers_test.go

cherry-pick of https://github.com/moby/moby/pull/37396 for 18.06
```
git checkout -b 18.06-backport-error_when_base_name_resolved_to_blank ce-engine/18.06
git cherry-pick -s -S -x c9542d313e2a52807644742e5fd684bc2de9f507
```
Fix: https://github.com/moby/moby/issues/37325

[18.06] Return error if basename is expanded to blank

---

hack/dockerfile/install/containerd.installer

backport of https://github.com/moby/moby/pull/37467 for 18.06;
```
git checkout -b 18.06-update-containerd ce-engine/18.06
git cherry-pick -s -S -x 9e773a12fb1cc5da7bec13d46fe04673a4593632 
```
Updates cri version to 1.0.4, to add `max-container-log-line-size`

[18.06] backport bump containerd daemon to v1.1.2

---

libcontainerd/client_local_windows.go

Backport of https://github.com/moby/moby/pull/37583 for 18.06
```
git checkout -b 18.06-backport-jjh.37562 upstream/18.06
git cherry-pick -s -S -x 5cfededc7ca552260f8eb7319184437a816e480d
```

[18.06] backport "don't invoke HCS shutdown if terminate called"

---

daemon/volumes.go

Backport of https://github.com/moby/moby/pull/37739.
```
git checkout -b 18.09-backport-pr37739 18.09
git cherry-pick 27d9030b2371aa4a6b167fded6b8dc25987a0af7
git push -f kir
```
Cherry-pick was clean, no issues.
------
In case a volume is specified via Mounts API, and SELinux is enabled,
the following error happens on container start:
> $ docker volume create testvol
> $ docker run --rm --mount source=testvol,target=/tmp busybox true
> docker: Error response from daemon: error setting label on mount
> source '': no such file or directory.
The functionality to relabel the source of a local mount specified via
Mounts API was introduced in commit 5bbf5cc and later broken by commit
e4b6adc, which removed setting mp.Source field.
With the current data structures, the host dir is already …

[18.09] backport "fix relabeling local volume source dir"

---

daemon/list.go
daemon/list_test.go

Backport of https://github.com/moby/moby/pull/37728 for 18.09. Cherry-pick was clean; no conflicts.
Commit https://github.com/moby/moby/pull/37462/commits/5c8da2e96738addd8a175e5b9a23b8c37d4a4dfe (https://github.com/moby/moby/pull/37462) updated the filtering behavior to match container-names without having to specify the leading slash.
This change caused a regression in situations where a regex was provided as filter, using an explicit leading slash (`--filter name=^/mycontainername`).
This fix changes the filters to match containers both with, and without the leading slash, effectively making the leading slash optional when filtering.
With this fix, filters with and without a leading slash produce the same result:
$ docker ps --filter name=^a
CONTAINER ID        IMAGE …

[18.09] backport: fix regression when filtering container names using a leading slash

---

client/client.go

backport:
* https://github.com/moby/moby/pull/37761 client: dial tls on Dialer if tls config is set
cherry pick https://github.com/moby/moby/pull/37761/commits/5974fc2 has no conflicts
```
$ git cherry-pick -s -x 5974fc2
[tls c2d0053207] client: dial tls on Dialer if tls config is set
Author: Tonis Tiigi <tonistiigi@gmail.com>
Date: Tue Sep 4 15:09:44 2018 -0700
1 file changed, 1 insertion(+), 1 deletion(-)
```

[18.09] client: dial tls on Dialer if tls config is set

---

daemon/attach.go
daemon/logger/adapter.go
daemon/logger/adapter_test.go
daemon/logger/journald/read.go
daemon/logger/jsonfilelog/jsonfilelog.go
daemon/logger/jsonfilelog/read_test.go
daemon/logger/local/local.go
daemon/logger/logger.go
daemon/logger/loggerutils/logfile.go
daemon/logger/loggerutils/logfile_test.go
daemon/logs.go
pkg/filenotify/poller.go

Backports of moby/moby#37734 and moby/moby#37576
> git checkout -b 18.09-backport-logs-follow 18.09
> git cherry-pick -x 88bcf15 dfbb64e fffa895
> git cherry-pick -x 2e4c2a6 d37a11b 916eabd f845d76
> git push -f kir 18.09-backport-logs-follow
Clean cherry-pick, no issues.

[18.09] backport "daemon.ContainerLogs(): fix resource leak on follow"

---

pkg/progress/progress.go

backport of https://github.com/moby/moby/pull/37780 for 18.09
```
git checkout -b 18.09_backport_fix-progress-panic ce-engine/18.09  
git cherry-pick -s -S -x 7dac70324d0ce6acd23458b0bef06f099837d648
```
I could not reproduce the panic in https://github.com/moby/moby/issues/37735, so here's a bandaid.

[18.09] backport pkg/progress: work around closing closed channel panic

---

daemon/config/config.go

- backported moby pr https://github.com/moby/moby/pull/37871
- no conflicts
```
> gcb cherry-37871 upstream/18.09
> git cherry-pick -x 8392d0930b511402aa7aa71ccfe6c0d4a8159237
[cherry-37871 66ed41aec] fixed the dockerd won't start bug when 'runtimes' field is defined in both daemon config file and cli flags
Date: Mon Sep 17 15:28:26 2018 -0700
1 file changed, 12 insertions(+), 2 deletions(-)
```
Signed-off-by: Anda Xu <anda.xu@docker.com>
(cherry picked from commit 8392d0930b511402aa7aa71ccfe6c0d4a8159237)

[18.09] backport fixing daemon won't start when "runtimes" option defined in both config file and cli

---

integration/network/service_test.go

backport of https://github.com/moby/moby/pull/37773 for 18.09
```
git checkout -b 18.09_backport_fix-TestServiceWithDefaultAddressPoolInit ce-engine/18.09
git cherry-pick -s -S -x 69d3a8936b8d91e43290aadb9f7ac2cd2929dc61  
```
Saw this in moby ci:
> 00:22:07.582 === RUN   TestServiceWithDefaultAddressPoolInit
> 00:22:08.887 --- FAIL: TestServiceWithDefaultAddressPoolInit (1.30s)
> 00:22:08.887 	daemon.go:290: [d905878b35bb9] waiting for daemon to start
> 00:22:08.887 	daemon.go:322: [d905878b35bb9] daemon started
> 00:22:08.888 panic: runtime error: index out of range [recovered]
> 00:22:08.889 	panic: runtime error: index out of range
> 00:22:08.889
> 00:22:08.889 goroutine 360 [running]:
> 00:22:08.889 testing.tRunner.func1(0xc42069d770)
> …

[18.09] backport TestServiceWithDefaultAddressPoolInit: avoid panic

---

daemon/trustkey.go

backport of https://github.com/moby/moby/pull/37847 for 18.09
```
git checkout -b 18.09_backport_more_permissive_daeon_conf_dir ce-engine/18.09
git cherry-pick -s -S -x cecd9817177093be99c1c9bb0dcf43ccec14ad1d
```
related: https://github.com/moby/moby/issues/37840, https://github.com/docker/cli/issues/1358, https://github.com/moby/moby/pull/37619
The `/etc/docker` directory is used both by the dockerd daemon
and the docker cli (if installed on the saem host as the daemon).
In situations where the `/etc/docker` directory does not exist,
and an initial `key.json` (legacy trust key) is generated (at the
default location), the `/etc/docker/` directory was created with
0700 permissions, making the directory only accessible by `root`.
Given that the `0600` …

[18.09] backport loosen permissions on /etc/docker directory

---

daemon/daemon_windows.go

Backport of https://github.com/moby/moby/pull/37774 for 18.09
```
git checkout -b 18.09_backport_windows-network-plugin-miss-fix ce-engine/18.09
git cherry-pick -s -S -x 6a1a4f97217b0a8635bc21fc86628f48bf8824d1
```
Similar to a related issue where previously, private Hyper-V networks
would each add 15 secs to the daemon startup, non-hns governed internal
networks are reported by hns as network type "internal" which is not
mapped to any network plugin (and thus we get the same plugin load retry
loop as before).
This issue hits Docker for Desktop because we setup such a network for
the Linux VM communication.

[18.09] Fix long startup on windows, with non-hns governed Hyper-V networks

---

daemon/graphdriver/devmapper/device_setup.go

Backport of https://github.com/moby/moby/pull/37951 for 18.09
```
git checkout -b 18.09_backport_fix-dm-errmsg ce-engine/18.09
git cherry-pick -s -S -x c378fb774e413ba8bf5cadf655d2b67e9c94245a
```
The parameter name was wrong, which may mislead a user.

[18.09] backport: gd/dm: fix error message

---

builder/builder-next/builder.go

Backport of https://github.com/moby/moby/pull/37980
Switches copy image to be one based in the `docker` docker hub organization.
Signed-off-by: Eli Uriegas <eli.uriegas@docker.com>
(cherry picked from commit 5cfd110c306d6a370307178b84d2b98d8598acc4)
Signed-off-by: Eli Uriegas <eli.uriegas@docker.com>

Switch copy image to a docker org based one

---

daemon/graphdriver/btrfs/btrfs.go
pkg/mount/sharedsubtree_linux.go

Backport of https://github.com/moby/moby/pull/38026. Clean cherry-pick, no issues.
```
git fetch engine
git checkout -b 18.09-backport-btrfs-prop engine/18.09
git cherry-pick -x f01297d1ae352bc2bf 8abadb36fa8149cd4 16d822bba8ac5ab22
git diff engine/18.09
git push -f kir 18.09-backport-btrfs-prop
```

[18.09] backport Fix mount propagation for btrfs

---

builder/builder-next/adapters/containerimage/pull.go

Backport of https://github.com/moby/moby/pull/38057
fixes a regression introduced in https://github.com/moby/moby/pull/37852 / https://github.com/docker/engine/pull/59
@tiborvass 
(cherry picked from commit c693d45acf74b87680ace0db8615f97bd6853598)

[18.09 backport] builder: fix private pulls on buildkit

---

hack/dockerfile/install/proxy.installer
vendor.conf
vendor/github.com/docker/libnetwork/controller.go
vendor/github.com/docker/libnetwork/ipvs/constants.go
vendor/github.com/docker/libnetwork/network.go
vendor/github.com/docker/libnetwork/osl/namespace_linux.go
vendor/github.com/docker/libnetwork/osl/sandbox.go
vendor/github.com/docker/libnetwork/sandbox.go
vendor/github.com/docker/libnetwork/service_linux.go

Bump libnetwork to 6da50d1978302f04c3e2089e29112ea24812f05b which
is the current tip of libnetwork's bump_18.09 branch to get the DSR load
balancing mode option changes for the 18.09 branch of Docker CE.
Signed-off-by: Chris Telfer <ctelfer@docker.com>

[18.09] Bump libnetwork to 6da50d19 for DSR load balancing changes

---

vendor.conf

Follow-up to https://github.com/docker/engine/pull/94. Let's add a note that this vendor comes from the bump_v18.09 branch, to prevent people from using a commit from upstream "master" instead.

[18.09] Add note that we use the bump_v18.09 branch for SwarmKit

---

Dockerfile
Dockerfile.e2e
Dockerfile.simple
Dockerfile.windows

Backport of https://github.com/moby/moby/pull/37727 for 18.09. Cherry-pick was clean; no conflicts.
Includes fixes to the go command, linker, and the net/http, mime/multipart,
ld/macho, bytes, and strings packages. See the Go 1.10.4 milestone on the
issue tracker for details:
https://github.com/golang/go/issues?q=milestone%3AGo1.10.4
(cherry picked from commit fe1fb7417c360f185ce608e0bfda41c0ef9fe364)

[18.09 backport] bump Go to 1.10.4

---

api/swagger.yaml

backport of https://github.com/moby/moby/pull/38040 for 18.09
```
git checkout -b 18.09_backport_document_service_version ce-engine/18.09
git cherry-pick -s -S -x 5bdfa19b8646839f9d704307aa6589c7d686db44
```
Hopefully this removes some confusion as to what this version number
should be.

[18.09 backport] Add more API doc details on service update version.

---

daemon/logger/jsonfilelog/jsonfilelog.go

backport of https://github.com/moby/moby/pull/37696 for 18.09
definitely not a critical backport, but it looks... sloppy :sweat_smile:
```
git checkout -b 18.09_backport_log_error_spelling ce-engine/18.09
git cherry-pick -s -S -x f962bd06ed8824d1f75d8546b428965cd61bdf7f
```

[18.09 backport] Fix incorrect spelling in error message

---

daemon/cluster/cluster.go
daemon/cluster/services.go
daemon/cluster/tasks.go

backport:
* https://github.com/moby/moby/pull/38103 cluster: set bigger grpc limit for array requests
to address:
* https://github.com/moby/moby/issues/37997 docker service ls | Error response from daemon: rpc error: code = ResourceExhausted desc = grpc: received message larger than max (5097134 vs. 4194304)
git cherry-pick https://github.com/moby/moby/pull/38103/commits/489b8eda6674523df8b82a210399b7d2954427d0
```
$ git cherry-pick -s -x 489b8eda6674523df8b82a210399b7d2954427d0
[grpc 6ca0546f25] cluster: set bigger grpc limit for array requests
Author: Tonis Tiigi <tonistiigi@gmail.com>
Date: Mon Oct 29 17:44:11 2018 -0700
3 files changed, 13 insertions(+), 5 deletions(-)
```
no conflicts

[18.09] cluster: set bigger grpc limit for array requests

---

daemon/cluster/cluster.go
daemon/cluster/services.go
daemon/cluster/tasks.go

backport:
* https://github.com/moby/moby/pull/38103 cluster: set bigger grpc limit for array requests
to address:
* https://github.com/moby/moby/issues/37997 docker service ls | Error response from daemon: rpc error: code = ResourceExhausted desc = grpc: received message larger than max (5097134 vs. 4194304)
git cherry-pick https://github.com/moby/moby/pull/38103/commits/489b8eda6674523df8b82a210399b7d2954427d0
```
$ git cherry-pick -s -x 489b8eda6674523df8b82a210399b7d2954427d0
[grpc1806 cdabbbf33c] cluster: set bigger grpc limit for array requests
Author: Tonis Tiigi <tonistiigi@gmail.com>
Date: Mon Oct 29 17:44:11 2018 -0700
3 files changed, 13 insertions(+), 5 deletions(-)
```
no conflicts

[18.06] cluster: set bigger grpc limit for array requests

---

vendor.conf
vendor/github.com/docker/swarmkit/manager/state/raft/transport/transport.go

Upstream changes: https://github.com/docker/swarmkit/compare/c82e409...6186e40
Brings in https://github.com/docker/swarmkit/pull/2775
continuation on previous fix #99 
This PR addresses the same grpc max message size issue for multi-manager swarm.
ping @andrewhsu @thaJeztah @dperny @tonistiigi

[18.09] Vendor swarmkit to 6186e40

---

daemon/info_unix.go
dockerversion/version_lib.go
hack/make/.go-autogen

backport of https://github.com/moby/moby/pull/37968 for 18.09
```
git checkout -b 18.09_backport_no_more_version_mismatch ce-engine/18.09
git cherry-pick -s -S -x c65f0bd13c85d29087419fa555281311091825e7
```
With containerd reaching 1.0, the runtime now has a stable API, so there's no need to do a check if the installed version matches the expected version.
Current versions of Docker now also package containerd and runc separately, and can be _updated_ separately.

[18.09 backport] remove version-checks for containerd and runc

---

integration/system/info_test.go

backport of https://github.com/moby/moby/pull/38115 for 18.09
```
git checkout -b 18.09_backport_fix_double_scheme ce-engine/18.09
git cherry-pick -s -S -x 14342046477b7ed87a9c5c451bb4520c7f6cabcc
```
`d.Sock()` already returns the socket-path including the `unix://` scheme.
Also removed `--iptables=false`, as it didn't really seem nescessary for this test.
Relates to https://github.com/moby/moby/pull/37684

[18.09 backport] Fix double "unix://" scheme in TestInfoAPIWarnings

---

daemon/graphdriver/overlay2/check.go
daemon/graphdriver/overlay2/overlay.go
daemon/graphdriver/overlay2/randomid.go

backport of https://github.com/moby/moby/pull/37993 for 18.09
fixes https://github.com/moby/moby/issues/37970
```
git checkout -b 18.09_backport_ovr2_index ce-engine/18.09
git cherry-pick -s -S -x a55d32546a8556f9e6cabbc99836b573b9944f0c
git cherry-pick -s -S -x 8422d85087bfa770b62ef4e1daaca95ee6783d86
```
cherry-pick was clean, no conflicts

[18.09 backport] overlay2: use index=off if possible (fix EBUSY on mount)

---

api/swagger.yaml
builder/builder-next/adapters/containerimage/pull.go
builder/builder-next/builder.go
vendor.conf
vendor/github.com/moby/buildkit/README.md
vendor/github.com/moby/buildkit/cache/contenthash/checksum.go
vendor/github.com/moby/buildkit/client/llb/source.go
vendor/github.com/moby/buildkit/client/llb/state.go
vendor/github.com/moby/buildkit/frontend/dockerfile/builder/build.go
vendor/github.com/moby/buildkit/frontend/dockerfile/dockerfile2llb/convert.go
vendor/github.com/moby/buildkit/frontend/dockerfile/dockerfile2llb/convert_norunmount.go
vendor/github.com/moby/buildkit/frontend/dockerfile/dockerfile2llb/convert_runmount.go
vendor/github.com/moby/buildkit/frontend/dockerfile/dockerfile2llb/convert_secrets.go
vendor/github.com/moby/buildkit/frontend/dockerfile/dockerfile2llb/convert_ssh.go
vendor/github.com/moby/buildkit/frontend/dockerfile/instructions/commands_nosecrets.go
vendor/github.com/moby/buildkit/frontend/dockerfile/instructions/commands_nossh.go
vendor/github.com/moby/buildkit/frontend/dockerfile/instructions/commands_runmount.go
vendor/github.com/moby/buildkit/frontend/dockerfile/instructions/commands_secrets.go
vendor/github.com/moby/buildkit/frontend/dockerfile/instructions/commands_ssh.go
vendor/github.com/moby/buildkit/frontend/dockerfile/shell/lex.go
vendor/github.com/moby/buildkit/session/session.go
vendor/github.com/moby/buildkit/solver/jobs.go
vendor/github.com/moby/buildkit/util/contentutil/refs.go
vendor/github.com/moby/buildkit/util/rootless/specconv/specconv_linux.go
vendor/github.com/moby/buildkit/vendor.conf
vendor/github.com/tonistiigi/fsutil/walker.go

Brings in following:
- fix docker system prune doesn't accept until filter https://github.com/moby/moby/pull/38238
- builder: avoid unset credentials in containerd https://github.com/moby/moby/pull/38226
- update buildkit to 0.3.3 https://github.com/moby/moby/pull/38244 , fixing:
- dockerfile: disable network for copy moby/buildkit#697
- fix private repos config resolve with external frontends moby/buildkit#729
- fix symlinks on reading Dockerfile moby/buildkit#733
- fix copying absolute symlinks moby/buildkit#712
Possibly could also use "builder: add workaround for gcr auth issue"  https://github.com/moby/moby/pull/38246 but needs upstream reviews first
@tiborvass @thaJeztah

[18.09 backport] BuildKit fixes for 18.09.1

---

api/swagger.yaml

These fields were added in https://github.com/moby/moby/pull/37558, so this will have to be back ported to docs for that version of the API
backport of https://github.com/moby/moby/pull/38218 for 18.09
```
git checkout -b 18.09_backport_fix_default_addr_pools_swagger ce-engine/18.09
git cherry-pick -s -S -x 2e8c913dbdfbba2591b6531ad2428c59eb261e0b
```

[18.09 backport] Add missing default address pool fields to swagger

---

api/server/router/swarm/cluster_routes.go

These options were added in API 1.39, so should be ignored when using an older version of the API.
relates to https://github.com/moby/moby/pull/37558
backport of https://github.com/moby/moby/pull/38196 for 18.09
```
git checkout -b 18.09_backport_fence_default_addr_pools ce-engine/18.09
git cherry-pick -s -S -x 7632ccbc66c82179547b96524672bd5082ae7481
```

[18.09 backport] Ignore default address-pools on API < 1.39

---

profiles/apparmor/apparmor.go
profiles/apparmor/template.go

backport of https://github.com/moby/moby/pull/37831 for 18.09
Carry https://github.com/moby/moby/pull/#36822
Fixes https://github.com/moby/moby/issues/#36809
```
git checkout -b 18.09_backport_apparmor_external_templates ce-engine/18.09
git cherry-pick -s -S -x 4822fb1e2423d88cdf0ad5d039b8fd3274b05401
```
In newer kernels, AppArmor will reject attempts to send signals to a
container because the signal originated from outside of that AppArmor
profile. Correct this by allowing all unconfined signals to be received.

[18.09 backport] apparmor: allow receiving of signals from 'docker kill'

---

client/request.go
client/request_test.go

client.checkResponseErr() was hanging and consuming infinite memory
when the serverResp.Body io.Reader returns infinite stream.
This commit prohibits reading more than 1MiB.
this is a backport of https://github.com/moby/moby/pull/38006

[18.09 backport] client: use io.LimitedReader for reading HTTP error

---

daemon/graphdriver/windows/windows.go

backport of https://github.com/moby/moby/pull/37712 for 18.09
fixes https://github.com/moby/moby/issues/36218 for 18.09
first commit was skipped, as the go-winio version was already bumped to v0.4.11 in https://github.com/docker/engine/pull/75
```
git checkout -b 18.09_backport_detach ce-engine/18.09
git cherry-pick -s -S -x efdad5374465a2a889d7572834a2dcca147af4fb
```
This is a fix for a few related scenarios where it's impossible to remove layers or containers
until the host is rebooted. Generally (or at least easiest to repro) through a forced daemon kill
while a container is running.
Possibly slightly worse than that, as following a host reboot, the scratch layer would possibly be leaked and
left on disk under the dataroot\windowsfilter directory after the container …

[18.09 backport] Windows: DetachVhd attempt in cleanup

---

daemon/logger/awslogs/cloudwatchlogs.go
daemon/logger/awslogs/cloudwatchlogs_test.go

backport of https://github.com/moby/moby/pull/37986 for 18.09
fixes https://github.com/moby/moby/issues/37747 for 18.09
```
git checkout -b 18.09_backport_moby_37747 ce-engine/18.09
git cherry-pick -s -S -x 1e8ef386279e2e28aff199047e798fad660efbdd
```
The CloudWatch Logs API defines its limits in terms of bytes, but its
inputs in terms of UTF-8 encoded strings.  Byte-sequences which are not
valid UTF-8 encodings are normalized to the Unicode replacement
character U+FFFD, which is a 3-byte sequence in UTF-8.  This replacement
can cause the input to grow, exceeding the API limit and causing failed
API calls.
This commit adds logic for counting the effective byte length after
normalization and splitting input without splitting valid …

[18.09 backport] awslogs: account for UTF-8 normalization in limits

---

hack/dockerfile/install/proxy.installer
vendor.conf
vendor/github.com/docker/libnetwork/iptables/iptables.go

Fixes a compatibility issue on recent debian versions, where iptables now uses
nft by default.
brings in https://github.com/docker/libnetwork/pull/2285 / https://github.com/docker/libnetwork/pull/2286
fixes https://github.com/moby/moby/issues/38099
full diff: https://github.com/docker/libnetwork/compare/6da50d1978302f04c3e2089e29112ea24812f05b...8bc51fd276b549b106dbc7bf8ab18b3a01d66e64

[18.09 backport] update libnetwork to fix iptables compatibility on debian

---

daemon/daemon_windows.go

backport of https://github.com/moby/moby/pull/38000 for 18.09
fixes https://github.com/moby/moby/issues/27524 
fixes https://github.com/moby/moby/issues/37873
fixes https://github.com/docker/for-win/issues/1822
closes https://github.com/moby/moby/pull/37065
closes https://github.com/moby/moby/pull/27730
```
git checkout -b 18.09_backport_processandiot ce-engine/18.09
git cherry-pick -s -S -x c907c2486c0850030f8ac1819ac8c87631472c68
```
cherry-pick was clean, no conflicts

[18.09 backport] Windows:Allow process isolation

---

hack/ci/windows.ps1

Backport of https://github.com/moby/moby/pull/38277 for 18.09
```
git checkout -b 18.09_backport_busybox ce-engine/18.09
git cherry-pick -s -S -x 14c8b67e51a8340284dfd8919843ce9edd1e5c71
```

[18.09 backport] Windows: Tie busybox to specific version

---

Dockerfile
Dockerfile.e2e
Dockerfile.simple
Dockerfile.windows

go1.10.5 (released 2018/11/02) includes fixes to the go command, linker,
runtime and the database/sql package. See the milestone on the issue
tracker for details:
List of changes; https://github.com/golang/go/issues?q=milestone%3AGo1.10.5

[18.09] Bump Go to 1.10.5

---

builder/builder-next/executor_unix.go

backport https://github.com/moby/moby/pull/38291
@thaJeztah @andrewhsu @tiborvass @fcrisciani 
This is a regression in `18.09` as `18.06-experimental` used host networking.

[18.09] builder: set externalkey option for faster hook processing

---

oci/defaults.go

Backport of https://github.com/moby/moby/pull/38299 for the 18.09 branch
fixes https://github.com/moby/moby/issues/38285 for 18.09 
```
git checkout -b 18.09_backport_mask_asound ce-engine/18.09
git cherry-pick -s -S -x 64e52ff3dbdb31adc0a9930b3ea74b04b0df8d86
```
While looking through the Moby source code was found /proc/asound to be shared
with containers as read-only.
This can lead to two information leaks.
---
**Leak of media playback status of the host**
Steps to reproduce the issue:
- Listen to music/Play a YouTube video/Do anything else that involves sound
output
- Execute docker run --rm ubuntu:latest bash -c "sleep 7; cat
/proc/asound/card*/pcm*p/sub*/status | grep state | cut -d ' ' -f2 | grep
RUNNING || echo 'not running'" …

[18.09 backport] Masked /proc/asound

---

hack/dockerfile/install/containerd.installer
hack/dockerfile/install/runc.installer

backport of https://github.com/moby/moby/pull/38328 for 18.09
```
git checkout -b 18.09_backport_containerd_v1.2.1-GA ce-engine/18.09 
git cherry-pick -s -S -x 1014b2bb66050a11bba833349346b35e6472688b
```

[18.09 backport] update just installer of containerd to 1.2.1

---

daemon/daemon_unix.go
hack/dockerfile/install/proxy.installer
pkg/sysinfo/sysinfo_linux.go
vendor.conf
vendor/github.com/containerd/containerd/oci/spec.go
vendor/github.com/containerd/containerd/runtime/v1/linux/proc/deleted_state.go
vendor/github.com/containerd/containerd/runtime/v1/linux/proc/exec.go
vendor/github.com/containerd/containerd/runtime/v1/linux/proc/exec_state.go
vendor/github.com/containerd/containerd/runtime/v1/linux/proc/init_state.go
vendor/github.com/containerd/containerd/runtime/v1/linux/proc/utils.go
vendor/github.com/containerd/containerd/vendor.conf
vendor/github.com/containerd/cri/vendor.conf
vendor/github.com/docker/libnetwork/sandbox_externalkey_unix.go
vendor/github.com/docker/libnetwork/vendor.conf
vendor/github.com/opencontainers/runc/libcontainer/cgroups/utils.go
vendor/github.com/opencontainers/runc/libcontainer/configs/config.go
vendor/github.com/opencontainers/runc/libcontainer/configs/intelrdt.go

backport of https://github.com/moby/moby/pull/38327 for 18.09
conflict in second commit (libnetwork vendor.conf), which is expected due to 18.09 vendoring from the bump_18.09 branch
ping @crosbymichael @andrewhsu @tiborvass @vdemeester PTAL

[18.09 backport] update containerd vendoring to v1.2.1

---

api/swagger.yaml

backport of https://github.com/moby/moby/pull/38354 for 18.09
fixes https://github.com/moby/moby/issues/38353 for 18.09

[18.09 backport] Swagger: fix definition of IPAM driver options

---

registry/registry.go

backport of https://github.com/moby/moby/pull/38348 for 18.09
fixes https://github.com/moby/moby/issues/38347 for 18.09
```
git checkout -b 18.09_backport_fix_panic ce-engine/18.09    
git cherry-pick -s -S -x a5c185b99404ea3fbab47ff9d7ba143392566bc1
```
This avoids the corner case where `via` is not nil, but has a length of 0,
so the updated code does not panic in that situation.

[18.09 engine] registry: use len(via)!=0 instead of via!=nil

---

pkg/truncindex/truncindex.go

Backport of https://github.com/moby/moby/pull/37904 for 18.09
fixes https://github.com/moby/moby/issues/38345 for 18.09
```Markdown
- Fix incorrect error message when finding a container by ID-prefix [moby/moby#37904](https://github.com/moby/moby/pull/37904)
```

[18.09 backport] fixes display text in Multiple IDs found with provided prefix

---

integration/internal/swarm/service.go
integration/service/create_test.go
vendor.conf
vendor/github.com/docker/swarmkit/manager/controlapi/service.go

Backports of;
- https://github.com/moby/moby/pull/38142 API: Add test for status code on conflicting service names
- https://github.com/docker/swarmkit/pull/2779 Return correct error-codes on conflicting names
Updates swarmkit to the latest version in the bump_18.09 branch;
https://github.com/docker/swarmkit/compare/6186e40fb04a7681e25a9101dbc7418c37ef0c8b...d61ff7666d7eba47137060c6c8fa8c29aa6198f5
- https://github.com/docker/swarmkit/pull/2788 Return correct error-codes on conflicting names (backport of https://github.com/docker/swarmkit/pull/2779)
- Addresses https://github.com/moby/moby/issues/38140. Relates to https://github.com/moby/moby/pull/38142 
```Markdown
- Fix API return code for conflicting service names …
```

[18.09 backport] API: fix status code on conflicting service names

---

hack/dockerfile/install/containerd.installer
vendor.conf
vendor/github.com/containerd/containerd/runtime/v1/linux/proc/exec.go
vendor/github.com/containerd/containerd/runtime/v1/linux/proc/init.go

Backport https://github.com/moby/moby/pull/38376
```
$ git cherry-pick -s -x e5d9d72
[cont d161dfe1a3] Update containerd to aa5e000c963756778ab3ebd1a12c6
Author: Michael Crosby <crosbymichael@gmail.com>
Date: Fri Dec 14 15:41:41 2018 -0500
4 files changed, 12 insertions(+), 2 deletions(-)
```
This includes a patch on top of containerd 1.2.1 to handle fifo
timeouts.
Signed-off-by: Michael Crosby <crosbymichael@gmail.com>
(cherry picked from commit e5d9d721626958a37dccfa0b234d9fc96d8c2bfb)
Signed-off-by: Andrew Hsu <andrewhsu@docker.com>

[18.09] Update containerd to aa5e000c963756778ab3ebd1a12c6

---

libcontainerd/client_daemon.go

Backport https://github.com/moby/moby/pull/38374
```
$ git cherry-pick -s -x 96e0ba1
[ctxt b6430ba413] Propagate context to exec delete
Author: Michael Crosby <crosbymichael@gmail.com>
Date: Fri Dec 14 11:56:23 2018 -0500
1 file changed, 1 insertion(+), 1 deletion(-)
```
Signed-off-by: Michael Crosby <crosbymichael@gmail.com>
(cherry picked from commit 96e0ba1afb228b48aa6e08a90cfc665083d24ccc)
Signed-off-by: Andrew Hsu <andrewhsu@docker.com>

[18.09] Propagate context to exec delete

---

libcontainerd/client_daemon.go

Talked with @tonistiigi about https://github.com/moby/moby/pull/38374#issuecomment-447675200 and worked out an alternative approach for the 18.09 codeline.
This PR reverts #139. Instead, an alternative backport https://github.com/moby/moby/pull/38383 is brought in.
```
$ git revert -s b6430ba
$ git cherry-pick -s -x 332f134
[d 6646d08782] libcontainerd: prevent exec delete locking
Author: Tonis Tiigi <tonistiigi@gmail.com>
Date: Mon Dec 17 12:22:37 2018 +0200
1 file changed, 7 insertions(+), 2 deletions(-)
```

[18.09] libcontainerd: prevent exec delete locking

---

integration/internal/swarm/service.go
integration/service/create_test.go
vendor.conf
vendor/github.com/docker/swarmkit/manager/controlapi/service.go

Reverts docker/engine#130
Unfortunately, since the Client library doesn't return the status code, the applications that rely on the error messages (though not a good idea), will be broken. Though this is a good fix, it will cause regression in a minor release and hence reverting the changes.

Revert "[18.09 backport] API: fix status code on conflicting service names"

---

hack/dockerfile/install/containerd.installer
vendor.conf
vendor/github.com/containerd/containerd/vendor.conf

backport of https://github.com/moby/moby/pull/38509 for 18.09.
Cherry-pick was clean
- Fix a bug that a container can't be stopped or inspected when its corresponding image is deleted
- Fix a bug that the cri plugin handles containerd events outside of k8s.io namespace

[18.09 backport] Bump containerd to v1.2.2

---

Dockerfile
pkg/archive/archive_unix_test.go

backport of https://github.com/moby/moby/pull/38292 for 18.09; cherry-pick was clean; no conflicts
Recent kernel has strict check for security.capability value.
Fix #38289
Signed-off-by: Akihiro Suda <suda.akihiro@lab.ntt.co.jp>
(cherry picked from commit 9ddd6e47a90ac056d242969ff72bf75a43cc0004)

[18.09 backport] pkg/archive: fix TestTarUntarWithXattr failure on recent kernel

---

Dockerfile
Dockerfile.e2e
Dockerfile.simple
Dockerfile.windows

See the milestone for details;
https://github.com/golang/go/issues?q=milestone%3AGo1.10.8+label%3ACherryPickApproved

[18.09] Bump Golang 1.10.8 (CVE-2019-6486)

---

daemon/daemon_windows.go

backport of https://github.com/moby/moby/pull/38580 for 18.09
for windows all networks are re-populated in the store during network controller initialization. In current version it also regenerate network Ids which may be referenced by other components and it may cause broken references to a networks. This commit avoids regeneration of network ids.

[18.09 backport] keep old network ids

---

integration-cli/docker_api_swarm_test.go
integration-cli/docker_cli_swarm_test.go

Backport https://github.com/moby/moby/pull/38423 to address flaky CI tests. Clean one, no conflicts.
```
git fetch engine
git checkout -b 18.06-backport-38423 engine/18.03
git fetch origin
git cherry-pick -x -s 02157c638ba0c325d8fd1debc1678e7e99eacfc1
```
----
Disabled these tests on s390x and ppc64le:
- TestAPISwarmLeaderElection
- TestAPISwarmRaftQuorum
- TestSwarmClusterRotateUnlockKey
because they are known to be flaky.
Signed-off-by: Olli Janatuinen <olli.janatuinen@gmail.com>
(cherry picked from commit 02157c638ba0c325d8fd1debc1678e7e99eacfc1)
Signed-off-by: Kir Kolyshkin <kolyshkin@gmail.com>

[18.09] Backport "Disabled these tests on s390x and ppc64le:"

---

pkg/namesgenerator/names-generator.go

backport of https://github.com/moby/moby/pull/38422 for 18.09. A bit unfortunate, but the inclusion of [Clifford Christopher Cocks](https://en.wikipedia.org/wiki/Clifford_Cocks) raised some eyebrows among users and customers, so let's backport this one
* Replaces `cocks` with `cerf` as the former might be perceived as
offensive by some people (as pointed out by @jeking3
[here](https://github.com/moby/moby/pull/37157#commitcomment-31758059))
* Removes a duplicate entry for `burnell`
* Re-arranges the entry for `sutherland` to ensure that the names are in
sorted order
* Adds entries for `shamir` and `wilbur`
Signed-off-by: Debayan De <debayande@users.noreply.github.com>
(cherry picked from commit e50f791d42d1167a5ef757b1aa179e84f0f81bba) …

[18.09 backport] Makes a few modifications to the name generator.

---

hack/make/.integration-daemon-start

backport of https://github.com/moby/moby/pull/38756 for 18.09
Here's what happens:
1. One runs `make binary` once
2. Days go by...
3. One makes changes to dockerd sources
4. One runs `make test-integration` to test the changes
5. One spends a long time figuring out why on Earth
those changes in step 3 are ignored by step 4.
6. One writes this patch
7. ...
8. PROFIT!!
OK, so `make test-integration` builds a dockerd binary
in bundles/dynbinary-daemon/, when starts a daemon instance
for testing. The problem is, the script that starts the
daemon sets PATH to try `bundles/binary-daemon/` first,
and `bundles/dynbinary-daemon/` second.
Signed-off-by: Kir Kolyshkin <kolyshkin@gmail.com>
(cherry picked from commit 228bc35e824d09a6f40d60619808462124f0af31)
Signed-off-by: Sebastiaan van Stijn …

[18.09 backport] make test-integration: use correct dockerd binary

---

integration/plugin/logging/helpers_test.go
integration/plugin/volumes/helpers_test.go
internal/test/fixtures/plugin/plugin.go

Thought I'd backport this one, as it caused some head-scratching when working on https://github.com/moby/moby/pull/38404#issuecomment-453307983
backport of https://github.com/moby/moby/pull/38543 for 18.09. Cherry-pick was clean; no conflicts.
By default, exec uses the environment of the current process, however,
if `exec.Env` is not `nil`, the environment is discarded:
https://github.com/golang/go/blob/e73f4894949c4ced611881329ff8f37805152585/src/os/exec/exec.go#L57-L60
> If Env is nil, the new process uses the current process's environment.
When adding a new environment variable, prepend the current environment,
to make sure it is not discarded.

[18.09 backport] Fix: plugin-tests discarding current environment

---

integration-cli/docker_cli_run_unix_test.go
integration-cli/requirements_unix_test.go
pkg/parsers/kernel/kernel_unix_test.go

backport of https://github.com/moby/moby/pull/38493 for 18.09; cherry-pick was clean
RHEL/CentOS 3.10 kernels report that kernel-memory accounting is supported,
but it actually does not work.
Runc (when compiled for those kernels) will be compiled without kernel-memory
support, so even though the daemon may be reporting that it's supported,
it actually is not.
This cause tests to fail when testing against a daemon that's using a runc
version without kmem support.
For now, skip these tests based on the kernel version reported by the daemon.
This should fix failures such as:
```
FAIL: /go/src/github.com/docker/docker/integration-cli/docker_cli_run_unix_test.go:499: DockerSuite.TestRunWithKernelMemory
assertion failed:
Command:  /usr/bin/docker run --kernel-memory 50M --name test1 busybox …
```

[18.09 backport] Skip kernel-memory tests on RHEL/CentOS daemons

---

container/container_unix.go
vendor.conf
vendor/github.com/containerd/continuity/LICENSE
vendor/github.com/containerd/continuity/README.md
vendor/github.com/containerd/continuity/fs/copy.go
vendor/github.com/containerd/continuity/fs/copy_linux.go
vendor/github.com/containerd/continuity/fs/copy_unix.go
vendor/github.com/containerd/continuity/fs/copy_windows.go

backport of https://github.com/moby/moby/pull/38316 for 18.09
fixes https://github.com/moby/moby/issues/38155 for 18.09
```
git checkout -b 18.09_backport_xattr_fix ce-engine/18.09    
git cherry-pick -s -S -x d0192ae154e6244edd4bf1bb298ea24146378058
```
full diff for the continuity bump; https://github.com/containerd/continuity/compare/bd77b46c8352f74eb12c85bdc01f4b90f69d66b4...004b46473808b3e7a4a3049c20e4376c91eb966d

[18.09 backport] Ignore xattr ENOTSUP errors on copy (fixes #38155)

---

daemon/graphdriver/copy/copy.go

backport of https://github.com/moby/moby/pull/38758 for 18.09. Cherry-pick was clean; no conflicts
Due to a bug in Golang (github.com/golang#27640), the "character device"
bit was omitted when checking file-modes with `os.ModeType`.
This bug was resolved in Go 1.12, but as a result, graphdrivers
would no longer recognize "device" files, causing pulling of
images that have a file with this filemode to fail;
failed to register layer:
unknown file type for /var/lib/docker/vfs/dir/.../dev/console
The current code checked for an exact match of Modes to be set. The
`os.ModeCharDevice` and `os.ModeDevice` bits will always be set in
tandem, however, because the code was only looking for an exact
match, this detection broke now that `os.ModeCharDevice` was added.
This patch changes the code to be …

[18.09 backport] Graphdriver: fix "device" mode not being detected if "character-device" bit is set

---

libcontainerd/supervisor/remote_daemon.go

backport of https://github.com/moby/moby/pull/38653 for 18.09
fixes https://github.com/moby/moby/issues/38636
addresses https://github.com/docker/for-linux/issues/517#issuecomment-466358473

[18.09 backport] Fix nil pointer derefence on failure to connect to containerd

---

daemon/start.go

backport of https://github.com/moby/moby/pull/38364 for 18.09
fixes https://github.com/moby/moby/issues/38346 for 18.09
containerd has two objects with regard to containers.
There is a "container" object which is metadata and a "task" which is
manging the actual runtime state.
When docker starts a container, it creartes both the container metadata
and the task at the same time. So when a container exits, docker deletes
both of these objects as well.
This ensures that if, on start, when we go to create the container metadata object
in containerd, if there is an error due to a name conflict that we go
ahead and clean that up and try again.
Signed-off-by: Brian Goff <cpuguy83@gmail.com>
(cherry picked from commit 5ba30cd1dc6000ee53b34f628cbff91d7f6d7231)
Signed-off-by: Sebastiaan van Stijn …

[18.09 backport] Delete stale containerd object on start failure

---

hack/ci/windows.ps1
integration-cli/docker_cli_build_test.go

backport of https://github.com/moby/moby/pull/38278 for 18.09. Cherry-pick was clean; no conflicts
This is a follow-on from https://github.com/moby/moby/pull/38277
but had to be done in a couple of stages to ensure that CI didn't
break. v1.1 of the busybox image is now based on a CMD of "sh"
rather than using an entrypoint. And it also uses the bin directory
rather than `c:\busybox`. This makes it look a lot closer to the
Linux busybox image, and means that a couple of Windows-isms in
CI tests can be reverted back to be identical to their Linux
equivalents.

[18.09 backport] Windows: Bump busybox to v1.1

---

pkg/archive/copy.go
pkg/archive/copy_unix_test.go

relates to https://github.com/moby/moby/pull/35739
As reported in docker/for-linux/issues/484, since Docker 18.06
docker cp with a destination file name fails with the following error:
> archive/tar: cannot encode header: Format specifies USTAR; and USTAR cannot encode Name="a_very_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx_long_filename_that_is_101_characters"
The problem is caused by changes in Go 1.10 archive/tar, which
mis-guesses the tar stream format as USTAR (rather than PAX),
which, in turn, leads to inability to specify file names
longer than 100 characters.
This tar stream is sent by TarWithOptions() (which, since we switched to
Go 1.10, explicitly sets format=PAX for every file, see FileInfoHeader(),
and before Go 1.10 it was PAX by default). Unfortunately, the …

[18.09 backport] pkg/archive:CopyTo(): fix for long dest filename

---

daemon/cluster/configs.go

backport of https://github.com/moby/moby/pull/38800 for 18.09

[18.09 backport] set bigger grpc limit for GetConfigs api

---

integration/build/build_session_test.go
integration/build/build_squash_test.go

backport of https://github.com/moby/moby/pull/38416 for 18.09
These tests were spinning up a new daemon, but after the daemon was spun up,
the default test-daemon was used by the client.

[18.09 backport] Fix TestBuildWithSession, TestBuildSquashParent  using wrong daemon during test

---

vendor.conf
vendor/github.com/docker/swarmkit/manager/controlapi/service.go
vendor/github.com/docker/swarmkit/manager/state/raft/util.go

full diff: https://github.com/docker/swarmkit/compare/6186e40fb04a7681e25a9101dbc7418c37ef0c8b...c66ed60822d3fc3bf6e17a505ee79014f449ef05
Relevant changes:
- https://github.com/docker/swarmkit/pull/2826 [18.09 backport] use a custom grpc dialer when managers are joining (backport of https://github.com/docker/swarmkit/pull/2802, which is a follow-up to https://github.com/docker/swarmkit/pull/2419)
- https://github.com/docker/swarmkit/pull/2801 [18.09 backport] Include old error-message for backward compatibility (backport of https://github.com/docker/swarmkit/pull/2797)
- https://github.com/docker/swarmkit/pull/2788 [18.09 backport] Return correct error-codes on conflicting names (backport of https://github.com/docker/swarmkit/pull/2779)

[18.09] bump swarmkit to c66ed60822d3fc3bf6e17a505ee79014f449ef05 (bump 18.09)

---

integration-cli/docker_cli_run_test.go

backport of https://github.com/moby/moby/pull/38907 for 18.09

[18.09 backport] Windows:Fix TestRunUserDefaults

---

integration-cli/docker_cli_run_test.go

backport of https://github.com/moby/moby/pull/38908 for 18.09

[18.09 backport] Windows (pre RS5) disableTestRunBindMounts

---

hack/dockerfile/install/containerd.installer
hack/dockerfile/install/runc.installer
vendor.conf
vendor/github.com/containerd/cgroups/README.md
vendor/github.com/containerd/cgroups/blkio.go
vendor/github.com/containerd/cgroups/cgroup.go
vendor/github.com/containerd/cgroups/control.go
vendor/github.com/containerd/cgroups/cpuset.go
vendor/github.com/containerd/cgroups/devices.go
vendor/github.com/containerd/cgroups/net_prio.go
vendor/github.com/containerd/cgroups/opts.go
vendor/github.com/containerd/cgroups/paths.go
vendor/github.com/containerd/cgroups/subsystem.go
vendor/github.com/containerd/cgroups/systemd.go
vendor/github.com/containerd/cgroups/utils.go

partial backport of https://github.com/moby/moby/pull/38873 (only the first and last commit); I don't think we need the containerd client and runc vendoring, but double check if it's needed 🙏

[18.09 backport] Update containerd v1.2.5, runc 2b18fe1d885ee5 binaries

---

daemon/monitor.go

backport of https://github.com/moby/moby/pull/38737 for 18.09
When manually stopping a container with a restart-policy, the container
would show as "restarting" in `docker ps` whereas its actual state
is "exited".
Stopping a container with a restart policy shows the container as "restarting"
docker run -d --name test --restart unless-stopped busybox false
docker stop test
docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS                       PORTS               NAMES
7e07409fa1d3        busybox             "false"             5 minutes ago       Restarting (1) 4 minutes ago                     test
However, inspecting the same container shows that it's exited:
docker inspect test --format '{{ json .State }}'
{
"Status": "exited",
"Running": …

[18.09 backport] Fix stopped containers with restart-policy showing as "restarting"

---

daemon/exec.go
integration/container/exec_test.go
integration/internal/container/ops.go

Backport of https://github.com/moby/moby/pull/38871 for 18.09
fixes https://github.com/moby/moby/issues/38865 for 18.09

[18.09 backport] Use original process spec for execs

---

api/server/backend/build/backend.go

Tagger was not called for BuildKit-mode.
Signed-off-by: Akihiro Suda <suda.akihiro@lab.ntt.co.jp>
(cherry picked from commit 7fc0f820ea1e9036a1466ee8ef7a7395b792623f)
Signed-off-by: Akihiro Suda <suda.akihiro@lab.ntt.co.jp>
---
https://github.com/moby/moby/pull/38902

[18.09 backport] builder-next: fix squash

---

daemon/container_operations_unix.go

backport of https://github.com/moby/moby/pull/38579 for 18.09
When running a container in the host's network namespace, the container
gets a copy of the host's resolv.conf (copied to `/etc/resolv.conf` inside
the container).
The current code always used the default (`/etc/resolv.conf`) path on the
host, irregardless if `systemd-resolved` was used or not.
This patch uses the correct file if `systemd-resolved` was detected
to be running.

[18.09 backport] Fix: network=host using wrong resolv.conf with systemd-resolved

---

vendor.conf
vendor/github.com/docker/swarmkit/manager/controlapi/node.go

full diff: https://github.com/docker/swarmkit/compare/c66ed60822d3fc3bf6e17a505ee79014f449ef05...19e791fd6dc76e8e894cbc99b77f946b7d00ebb9
includes https://github.com/docker/swarmkit/pull/2842 / https://github.com/docker/swarmkit/pull/2806 "Fix leaking task resources when nodes are deleted"

[18.09] bump docker/swarmkit 19e791fd6dc76e8e894cbc99 (18.09 branch)

---

vendor.conf
vendor/github.com/docker/libnetwork/drivers/windows/overlay/joinleave_windows.go
vendor/github.com/docker/libnetwork/drivers/windows/overlay/ov_endpoint_windows.go
vendor/github.com/docker/libnetwork/drivers/windows/overlay/peerdb_windows.go

This commit brings in https://github.com/docker/libnetwork/pull/2356 and https://github.com/docker/libnetwork/pull/2357. Adds a workaround for a WS2016 HNS race issue by serializing the L2 Table programming across networks.
Signed-off-by: Madhu Venugopal <madhu@docker.com>

[18.09 backport] Vendor Libnetwork c902989

---

vendor.conf
vendor/github.com/moby/buildkit/solver/llbsolver/ops/exec.go

brings in moby/buildkit#911 [docker-18.09] llbsolver: fix selectors dedupe
(backport of https://github.com/moby/buildkit/pull/858)
fixes https://github.com/moby/moby/issues/38964

[18.09] bump buildkit ed4da8b4a9661f278ae8433056ca37d0727c408b (docker-18.09 branch)

---

hack/dockerfile/install/proxy.installer
vendor.conf
vendor/github.com/docker/libnetwork/agent.go
vendor/github.com/docker/libnetwork/drivers/windows/overlay/ov_endpoint_windows.go
vendor/github.com/docker/libnetwork/drivers/windows/overlay/ov_network_windows.go
vendor/github.com/docker/libnetwork/drivers/windows/port_mapping.go
vendor/github.com/docker/libnetwork/drivers/windows/windows.go
vendor/github.com/docker/libnetwork/portallocator/portallocator_windows.go
vendor/github.com/docker/libnetwork/portmapper/mapper.go
vendor/github.com/docker/libnetwork/portmapper/mapper_linux.go
vendor/github.com/docker/libnetwork/portmapper/mapper_windows.go
vendor/github.com/docker/libnetwork/portmapper/proxy_windows.go

carrying #200 for seb
full diff: https://github.com/docker/libnetwork/compare/c9029898e32f7c89bbb81511fbb721df252ce61a...872f0a83c98add6cae255c8859e29532febc0039
- docker/libnetwork#2354 [18.09 backport] Cleanup the cluster provider when the agent is closed
- backport of docker/libnetwork#2307 Fix for problem where agent is stopped and does not restart
- fixes docker/for-linux#495 Docker swarm overlay networking not working after --force-new-cluster
- docker/libnetwork#2369 [18.09 BACKPORT] Pick a random host port if the user does not specify a host port
- backport of docker/libnetwork#2368 (windows) Pick a random host port if the user does not specify a host port

[18.09] bump libnetwork 872f0a8

---

Dockerfile
Dockerfile.e2e
Dockerfile.simple
Dockerfile.windows
integration-cli/docker_api_containers_test.go
integration/build/build_test.go
integration/container/ipcmode_linux_test.go
integration/container/run_linux_test.go
integration/image/list_test.go
integration/system/ping_test.go
integration/system/uuid_test.go
integration/volume/volume_test.go

backport of https://github.com/moby/moby/pull/39179 for 19.03
built on top of https://github.com/docker/engine/pull/207 to get a clean cherry-pick

[19.03 backport] Bump Golang 1.12.5

---

Dockerfile.e2e
integration-cli/docker_api_containers_test.go
integration/build/build_test.go
integration/container/ipcmode_linux_test.go
integration/container/run_linux_test.go
integration/image/list_test.go
integration/system/ping_test.go
integration/system/uuid_test.go
integration/volume/volume_test.go

backports for 19.03 of;
- https://github.com/moby/moby/pull/39115 Dockerfile.e2e fix TestBuildPreserveOwnership
- https://github.com/moby/moby/pull/39116 Improve Dockerfile.e2e
- https://github.com/moby/moby/pull/39150 Dockerfile.e2e: copy test sources

[19.03 backport] backport Dockerfile.e2e fixes

---

cmd/dockerd/config_common_unix.go
cmd/dockerd/config_unix.go
cmd/dockerd/daemon.go
cmd/dockerd/daemon_unix.go
cmd/dockerd/docker.go
contrib/dockerd-rootless.sh
docs/rootless.md
hack/dockerfile/install/rootlesskit.installer
opts/hosts.go
rootless/rootless.go

backports for 19.03 of;
- https://github.com/moby/moby/pull/39112 rootless: optional support for lxc-user-nic SUID binary
- https://github.com/moby/moby/pull/39138 dockerd: fix rootless detection (alternative to https://github.com/moby/moby/pull/39024)
fixes https://github.com/moby/moby/issues/38702
fixes https://github.com/moby/moby/issues/39009

[19.03 backport] backport rootless fixes

---

daemon/cluster/executor/container/controller.go
integration/service/update_test.go

backport of https://github.com/moby/moby/pull/39174 for 19.03
make sure the LB sandbox is removed when a service is updated
with a --network-rm option

[19.03 backport] Remove a network during task SHUTDOWN instead of REMOVE to

---

hack/dockerfile/install/runc.installer
vendor.conf
vendor/github.com/opencontainers/runc/vendor.conf
vendor/github.com/opencontainers/selinux/go-selinux/selinux_linux.go

backport of https://github.com/moby/moby/pull/39143 for 19.03

[19.03 backport] Bump runc 1.0.0-rc8, opencontainers/selinux v1.2.2

---

builder/builder-next/adapters/containerimage/pull.go

backport of https://github.com/moby/moby/pull/39183 for 19.03
fixes https://github.com/moby/moby/issues/39182 for 19.03

[19.03 backport] builder-next: fix gcr workaround token cache

---

internal/test/daemon/daemon.go

backport of https://github.com/moby/moby/pull/39197 for 19.03
As of Go 1.12, the `testing` package panics if a goroutine logs to a
`testing.T` after the relevant test has completed. This was not
documented as a change at all; see the commit
95d06ab6c982f58b127b14a52c3325acf0bd3926 in the Go repository for the
relevant change.
At any point in the integration tests, tests could panic with the
message "Log in goroutine after TEST_FUNCTION has completed". This was
exacerbated by less direct logging I/O, e.g. running `make test` with
its output piped instead of attached to a TTY.
The most common cause of panics was that there was a race condition
between an exit logging goroutine and the `StopWithError` method:
`StopWithError` could return, causing the calling test method to return,
causing …

[19.03 backport] Ensure all integration daemon logging happens before test exit

---

volume/mounts/linux_parser.go
volume/mounts/parser_test.go

backport of https://github.com/moby/moby/pull/39251 for 19.03
fixes https://github.com/docker/for-linux/issues/674 for 19.03
Errors were being ignored and always telling the user that the path
doesn't exist even if it was some other problem, such as a permission
error.

[19.03 backport] Fix error handling for bind mount spec parser.

---

hack/dockerfile/install/proxy.installer
vendor.conf
vendor/github.com/docker/libnetwork/drivers/windows/port_mapping.go
vendor/github.com/docker/libnetwork/drivers/windows/windows.go

backport of https://github.com/moby/moby/pull/39246 for 19.03
full diff: https://github.com/docker/libnetwork/compare/9ff9b57c344df5cd47443ad9e65702ec85c5aeb0...5ac07abef4eee176423fdc1b870d435258e2d381
brings in:
- docker/libnetwork#2376 Forcing a nil IP specified in PortBindings to IPv4zero (0.0.0.0)

[19.03 backport] bump libnetwork 5ac07abef4eee176423fdc1b870d435258e2d381

---

client/ping.go

backport of https://github.com/moby/moby/pull/39206 for 19.03. Relates to https://github.com/docker/cli/issues/1739
When we see an `ECONNREFUSED` (or equivalent) from an attempted `HEAD` on the
`/_ping` endpoint there is no point in trying again with `GET` since the server
is not responding/available at all.
Once vendored into the cli this will partially mitigate https://github.com/docker/cli/issues/1739
("Docker commands take 1 minute to timeout if context endpoint is unreachable")
by cutting the effective timeout in half.

[19.03 backport] client: do not fallback to GET if HEAD on _ping fail to connect

---

integration-cli/docker_cli_run_unix_test.go

backport of https://github.com/moby/moby/pull/39254 - cherry pick was clean
`chmod` is a legacy syscall, and not present on arm64, which caused this test to fail.
Add `fchmodat` to the profile so that this test can run both on x64 and arm64.

[19.03 backport] Update TestRunWithDaemonDefaultSeccompProfile for ARM64

---

integration-cli/docker_cli_daemon_test.go

backport of https://github.com/moby/moby/pull/39226 for 19.03

[19.03 backport] explicitly set filesystem type for mount to avoid 'invalid argument' error on arm

---

integration-cli/docker_cli_search_test.go

backport of https://github.com/moby/moby/pull/39257 for 18.09
built on top of https://github.com/docker/engine/pull/226 to get a clean cherry-pick

[19.03 backport] Remove TestSearchCmdOptions test

---

integration-cli/docker_cli_search_test.go

backport of https://github.com/moby/moby/pull/39243
Sometimes this test fails (allegedly due to problems with Docker Hub),
but it fails later than it should, for example:
> 01:20:34.845 assertion failed: expression is false: strings.Count(outSearchCmdStars, "[OK]") <= strings.Count(outSearchCmd, "[OK]"): The quantity of images with stars should be less than that of all images: <...>
This, with non-empty list of images following, means that the initial
`docker search busybox` command returned not enough results. So, add
a check that `docker search busybox` returns something.
While at it,
* raise the number of stars to 10;
* simplify check for number of lines (no need to count [OK]'s);
* improve error message.

[19.03 backport] int-cli/TestSearchCmdOptions: fail earlier

---

daemon/daemon_unix.go
daemon/daemon_unix_test.go

backport of https://github.com/moby/moby/pull/39212 for 19.03
fix a bug which cause an error like :
`write 4349:48 0 to blkio.throttle.read_bps_device: write /sys/fs/cgroup/blkio/xxx/cid/blkio.throttle.read_bps_device: no such device`
the container has config `"BlkioDeviceReadBps":[{"Path":"/dev/vdt","Rate":0}]`
and I foud `stat /dev/vdt` and `ls -l /dev/vdt` has different out of device number, which is correct:
```
#ls -l /dev/vdt
brw-rw---- 1 root disk 253, 304 May 9 17:03 /dev/vdt
#stat /dev/vdt | grep type
Device: 6h/6d Inode: 56051004	Links: 1	Device type: fd, 130
```
Someone in docker forum ran into the same problem: https://forums.docker.com/t/docker-run-device-read-bps-option-not-working/68044 in his case is the major number …

[19.03 backport] bugfix: fetch the right device number which great than 255

---

api/swagger.yaml

backport of
- https://github.com/moby/moby/pull/39263 API: Change type of RemotrAddrs to array of strings in operation SwarmJoin
- https://github.com/moby/moby/pull/39264 API: Move "x-nullable: true" from type PortBinding to type PortMap
- https://github.com/moby/moby/pull/39265 Update docs to remove restriction of tty resize

[19.03 backport] swagger fixes

---

builder/builder-next/executor_unix.go

backport https://github.com/moby/moby/pull/39202

[19.03 backport] builder-next: support DOCKER_RAMDISK

---

daemon/cluster/executor/container/container.go

backport of https://github.com/moby/moby/pull/39190
fixes https://github.com/moby/moby/issues/33538
Today `$ docker service create --limit-cpu` configures a containers `CpuPeriod` and `CpuQuota` variables, this commit switches this to configure a containers `NanoCpu` variable instead to try and fix moby/moby#33538 and provide support for limiting CPU on Windows Workloads.
This change makes  `$ docker service create --limit-cpu` the same as `$ docker run --cpu` as the later is supported on windows. https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-containers/resource-controls
The reason this change was required is because CPU Period is not supported on Windows today:
```
$ docker service create --limit-cpu "1.5" --name demo hello-world …
```

[19.03 backport] Switch swarmmode services to NanoCpu

---

internal/test/environment/environment.go

backport of https://github.com/moby/moby/pull/39215 for 19.03

[19.03 backport] Consider WINDOWS_BASE_IMAGE_TAG override when setting Windows base image for tests

---

hack/dockerfile/install/proxy.installer
vendor.conf
vendor/github.com/docker/libnetwork/drivers/windows/port_mapping.go
vendor/github.com/docker/libnetwork/drivers/windows/windows.go

bumping libnetwork on 18.09 to include docker/libnetwork#2377 for ENGCORE-791

[18.09] Backport Forcing a nil IP specified in PortBindings to IPv4 zero (0.0.0.0).

---

builder/builder-next/adapters/containerimage/pull.go

backport of https://github.com/moby/moby/pull/39211 for 18.09
ping @tonistiigi @tiborvass PTAL

[18.09 backport] builder-next: call stopprogress on download error

---

daemon/cluster/executor/container/controller.go

backport of https://github.com/moby/moby/pull/39242 for 19.03
Make sure adapter.removeNetworks executes during task Remove
Fixes https://github.com/moby/moby/issues/39225

[19.03 backport] Network not deleted after stack is removed

---

api/server/backend/build/backend.go

backport of https://github.com/moby/moby/pull/39310 for 19.03
Fixes a panic on `docker build -t foo -o - . >/dev/null`

[19.03 backport] build: fix panic when exporting to tar

---

daemon/archive.go
daemon/export.go
pkg/chrootarchive/archive.go
pkg/chrootarchive/archive_unix.go
pkg/chrootarchive/archive_unix_test.go
pkg/chrootarchive/archive_windows.go
pkg/chrootarchive/init_unix.go

backport of https://github.com/moby/moby/pull/39292 for 19.03
This is useful for preventing CVE-2018-15664 where a malicious container
process can take advantage of a race on symlink resolution/sanitization.
Before this change chrootarchive would chroot to the destination
directory which is attacker controlled. With this patch we always chroot
to the container's root which is not attacker controlled.
replaces https://github.com/moby/moby/pull/39252

[19.03 backport] Pass root to chroot to for chroot Tar/Untar (CVE-2018-15664)

---

api/swagger.yaml

backport of https://github.com/moby/moby/pull/39248 for 19.03

[19.03 backport] API: Set format of body parameter in operation PutContainerArchive to "binary"

---

api/swagger.yaml
daemon/daemon_unix.go
docs/api/version-history.md
docs/rootless.md

backport of https://github.com/moby/moby/pull/39299  https://github.com/moby/moby/pull/39309 for 19.03
Signed-off-by: Akihiro Suda <akihiro.suda.cz@hco.ntt.co.jp>
Previously `docker info` had reported "cgroupfs" as the cgroup driver
but the driver wasn't actually used at all.
This PR reports "none" as the cgroup driver so as to avoid confusion.
e.g. kubeadm/kubelet will detect cgroupless-ness by checking this docker
info field. https://github.com/rootless-containers/usernetes/blob/297f077e9a062778e1cadba962b7b5e04cdc27eb/src/patches/kubernetes/0004-kubelet-new-feature-gate-SupportNoneCgroupDriver.patch#L319
Note that user still cannot specify `native.cgroupdriver=none` manually.
See `daemon/daemon_unix.go`
```console
$ docker info …
```

[19.03 backport] info: report cgroup driver as "none" when running rootless

---

hack/ci/windows.ps1

backport of https://github.com/moby/moby/pull/39259 for 19.03
cherry-pick was clean

[19.03 backport] Windows CI - Corrected LOCALAPPDATA location

---

layer/layer_store.go
layer/migration.go
layer/migration_test.go
layer/mounted_layer.go

backport of https://github.com/moby/moby/pull/39135 and https://github.com/moby/moby/pull/39209 for 19.03
cherry-picks were clean

[19.03 backport] backport layer store optimizations

---

daemon/cluster/nodes.go
daemon/cluster/secrets.go

backport of https://github.com/moby/moby/pull/39306 for 19.03
Increases the max recieved gRPC message size for Node and Secret list
operations. This has already been done for the other swarm types, but
was not done for these.

[19.03 backport] Increase max recv gRPC message size for nodes and secrets

---

integration/service/update_test.go
vendor.conf
vendor/github.com/docker/swarmkit/manager/orchestrator/update/updater.go

backport of https://github.com/moby/moby/pull/39281 for 19.03.
Local changes applied cleanly, but the vendor.conf did not; fixed by changing `vendor.conf` to point to the bump_v19.03 branch (which includes https://github.com/docker/swarmkit/pull/2863), and running `vndr` again.
Reverts the change to swarmkit that made all updates set UpdateStatus to Completed.
See docker/swarmkit#2861
related: https://github.com/docker/swarmkit/pull/2804, https://github.com/moby/moby/pull/38520
fixes https://github.com/docker/swarmkit/issues/2861
fixes https://github.com/moby/moby/issues/39023
Returned the integration test to the way it was before

[19.03 backport] Revert docker/swarmkit#2804

---

daemon/archive.go
daemon/export.go
pkg/chrootarchive/archive.go
pkg/chrootarchive/archive_unix.go
pkg/chrootarchive/archive_unix_test.go
pkg/chrootarchive/archive_windows.go
pkg/chrootarchive/init_unix.go

backport of https://github.com/moby/moby/pull/39292 for 18.09
This is useful for preventing CVE-2018-15664 where a malicious container
process can take advantage of a race on symlink resolution/sanitization.
Before this change chrootarchive would chroot to the destination
directory which is attacker controlled. With this patch we always chroot
to the container's root which is not attacker controlled.
replaces https://github.com/moby/moby/pull/39252

[18.09 backport] Pass root to chroot to for chroot Tar/Untar (CVE-2018-15664)

---

pkg/idtools/idtools.go
pkg/idtools/idtools_test.go

backport of https://github.com/moby/moby/pull/39288 for 19.03
Moby currently sorts uid and gid ranges in id maps. This causes subuid
and subgid files to be interpreted wrongly.
The subuid file
```
> cat /etc/subuid
jonas:100000:1000
jonas:1000:1
```
configures that the container uids 0-999 are mapped to the host uids
100000-100999 and uid 1000 in the container is mapped to uid 1000 on the
host. The expected uid_map is:
```
> docker run ubuntu cat /proc/self/uid_map
0     100000       1000
1000       1000          1
```
Moby currently sorts the ranges by the first id in the range. Therefore
with the subuid file above the uid 0 in the container is mapped to uid
100000 on host and the uids 1-1000 in container are mapped to the uids
1-1000 on the host. The resulting uid_map is:
```
> docker …
```

[19.03 backport] Stop sorting uid and gid ranges in id maps

---

hack/dockerfile/install/proxy.installer

backport of https://github.com/moby/moby/pull/39337 for 19.03
> missed that https://github.com/moby/moby/pull/39295 didn't update `LIBNETWORK_COMMIT`
comparison of changes: https://github.com/docker/libnetwork/compare/5ac07abef4eee176423fdc1b870d435258e2d381...fc5a7d91d54cc98f64fc28f9e288b46a0bee756c

[19.03 backport] Re-align proxy commit with libnetwork vendor

---

api/swagger.yaml
docs/api/version-history.md

backport of https://github.com/moby/moby/pull/39279 for 19.03
original fix at [#28923](https://github.com/moby/moby/pull/28923), but lack of bringing change to swagger.
add copyUIDGID param to swagger.yaml
No need

[19.03 backport] fix: fix lack of copyUIDGID in swagger.yaml

---

cmd/dockerd/daemon.go
cmd/dockerd/daemon_unix.go
integration-cli/docker_cli_ps_test.go
internal/test/daemon/daemon.go

backports for 19.03 of;
- https://github.com/moby/moby/pull/39105 Optimize test daemon startup 
- https://github.com/moby/moby/pull/39325 Harden TestPsListContainersFilterExited

[19.03 backport] test-fixes and improvements

---

layer/layer_store.go
layer/migration.go
layer/migration_test.go
layer/mounted_layer.go

backport of https://github.com/moby/moby/pull/39135 and https://github.com/moby/moby/pull/39209 for 18.09
cherry-picks were clean

[18.09 backport ENGCORE-830] layer store optimizations

---

daemon/graphdriver/aufs/aufs.go
daemon/graphdriver/aufs/mount.go

Backport moby/moby#39107. Clean cherry-pick, no issues.

[19.03 backport ENGCORE-831] aufs optimizations #39107

---

daemon/archive.go
daemon/export.go
integration/container/copy_test.go
pkg/archive/archive_unix.go
pkg/chrootarchive/archive.go
pkg/chrootarchive/archive_unix.go
pkg/chrootarchive/archive_unix_test.go
pkg/chrootarchive/archive_windows.go
pkg/chrootarchive/init_unix.go

Reverts #275 which reverted #254 and cherry-picks the needed fix from https://github.com/moby/moby/pull/39357
Related to https://github.com/moby/moby/issues/39348

[19.03] Add chroot back to Tar/Untar without the previously introduced regression

---

integration/system/info_test.go

backport of https://github.com/moby/moby/pull/38451 for 18.09
This test starts a new daemon, which will fail when testing
against a remote daemon;
--- FAIL: TestInfoAPIWarnings (0.00s)
info_test.go:53: failed to start daemon with arguments [-H=0.0.0.0:23756 -H=unix:///tmp/docker-integration/d5153ebcf89ef.sock] : [d5153ebcf89ef] could not find docker binary in $PATH: exec: "dockerd": executable file not found in $PATH

[18.09 backport] Skip TestInfoAPIWarnings on remote daemons

---

hack/make.ps1

backport of https://github.com/moby/moby/pull/39117 for 18.09
Checks for environment variable VERSION if it exists then it sets dockerVersion to VERSION

[18.09 backport] Add ability to override the version in make.ps1

---

integration-cli/docker_cli_run_unix_test.go

backport of https://github.com/moby/moby/pull/39254 - cherry pick was clean
`chmod` is a legacy syscall, and not present on arm64, which caused this test to fail.
Add `fchmodat` to the profile so that this test can run both on x64 and arm64.

[18.09 backport] Update TestRunWithDaemonDefaultSeccompProfile for ARM64

---

internal/test/daemon/daemon.go

backport of https://github.com/moby/moby/pull/39197 for 18.09
As of Go 1.12, the `testing` package panics if a goroutine logs to a
`testing.T` after the relevant test has completed. This was not
documented as a change at all; see the commit
95d06ab6c982f58b127b14a52c3325acf0bd3926 in the Go repository for the
relevant change.
At any point in the integration tests, tests could panic with the
message "Log in goroutine after TEST_FUNCTION has completed". This was
exacerbated by less direct logging I/O, e.g. running `make test` with
its output piped instead of attached to a TTY.
The most common cause of panics was that there was a race condition
between an exit logging goroutine and the `StopWithError` method:
`StopWithError` could return, causing the calling test method to return,
causing …

[18.09 backport] Ensure all integration daemon logging happens before test exit

---

integration-cli/docker_cli_search_test.go

backport of https://github.com/moby/moby/pull/39257 for 18.09
built on top of https://github.com/docker/engine/pull/225 to get a clean cherry-pick

[18.09 backport] Remove TestSearchCmdOptions test

---

integration-cli/docker_cli_search_test.go

backport of https://github.com/moby/moby/pull/39243
Sometimes this test fails (allegedly due to problems with Docker Hub),
but it fails later than it should, for example:
> 01:20:34.845 assertion failed: expression is false: strings.Count(outSearchCmdStars, "[OK]") <= strings.Count(outSearchCmd, "[OK]"): The quantity of images with stars should be less than that of all images: <...>
This, with non-empty list of images following, means that the initial
`docker search busybox` command returned not enough results. So, add
a check that `docker search busybox` returns something.
While at it,
* raise the number of stars to 10;
* simplify check for number of lines (no need to count [OK]'s);
* improve error message.

[18.09 backport] int-cli/TestSearchCmdOptions: fail earlier

---

hack/ci/windows.ps1

backport of https://github.com/moby/moby/pull/39259 for 18.09
cherry-pick was clean

[18.09 backport] Windows CI - Corrected LOCALAPPDATA location

---

api/swagger.yaml
docs/api/version-history.md

backport of
- https://github.com/moby/moby/pull/39263 API: Change type of RemotrAddrs to array of strings in operation SwarmJoin
- https://github.com/moby/moby/pull/39264 API: Move "x-nullable: true" from type PortBinding to type PortMap
- https://github.com/moby/moby/pull/39265 Update docs to remove restriction of tty resize
- https://github.com/moby/moby/pull/39248 API: Set format of body parameter in operation PutContainerArchive to "binary" 
- https://github.com/moby/moby/pull/39279 fix: fix lack of copyUIDGID in swagger.yaml

[18.09 backport] Swagger fixes

---

hack/ci/windows.ps1
hack/make.ps1
integration/internal/container/container.go
integration/volume/volume_test.go

backport of https://github.com/moby/moby/pull/39240 for 18.09

[18.09 backport] Enable integrations API tests for Windows CI

---

daemon/daemon_unix.go
daemon/daemon_unix_test.go

backport of https://github.com/moby/moby/pull/39212 for 18.09. Some conflicts in the test-file due to other changes not being in this branch, but trivial to resolve
fix a bug which cause an error like :
`write 4349:48 0 to blkio.throttle.read_bps_device: write /sys/fs/cgroup/blkio/xxx/cid/blkio.throttle.read_bps_device: no such device`
the container has config `"BlkioDeviceReadBps":[{"Path":"/dev/vdt","Rate":0}]`
and I foud `stat /dev/vdt` and `ls -l /dev/vdt` has different out of device number, which is correct:
```
#ls -l /dev/vdt
brw-rw---- 1 root disk 253, 304 May 9 17:03 /dev/vdt
#stat /dev/vdt | grep type
Device: 6h/6d Inode: 56051004	Links: 1	Device type: fd, 130
```
Someone in docker forum ran into the same problem: …

[18.09 backport] bugfix: fetch the right device number which great than 255

---

integration-cli/docker_cli_daemon_test.go

backport of https://github.com/moby/moby/pull/39226 for 18.09

[18.09 backport] explicitly set filesystem type for mount to avoid 'invalid argument' error on arm

---

image/rootfs.go

backport of https://github.com/moby/moby/pull/38888 for 18.09
append(newRoot.DiffIDs) without element does nothing,
so it's probably not what was intended. Changed code
to perform a slice copying instead.
Fixes #38834.

[18.09 backport] image: do actual RootFS.DiffIDs copying in Clone()

---

daemon/cluster/nodes.go
daemon/cluster/secrets.go

backport of https://github.com/moby/moby/pull/39306 for 18.09
Increases the max recieved gRPC message size for Node and Secret list
operations. This has already been done for the other swarm types, but
was not done for these.
Signed-off-by: Drew Erny <drew.erny@docker.com>
(cherry picked from commit a0903e1fa3eca32065c7dbfda8d1e0879cbfbb8f)

[18.09 backport] Increase max recv gRPC message size for nodes and secrets

---

hack/dockerfile/install/containerd.installer
hack/dockerfile/install/runc.installer

backport for the 18.09 branch of:
- https://github.com/moby/moby/pull/39016 Bump containerd v1.2.6, runc 029124da7af7360afa781a0234d1b083550f797c
- *_the last commit (https://github.com/moby/moby/pull/39016/commits/c28171c7c4984bfd0be002d1622fab0779ff573b) was omitted, as it didn't appear to have relevant changes_*
- https://github.com/moby/moby/pull/39143 Bump runc 1.0.0-rc8, opencontainers/selinux v1.2.2
- only the runc binary 1.0.0-rc8 bump

[18.09 backport] Bump containerd v1.2.6, runc v1.0.0-rc8

---

volume/mounts/linux_parser.go
volume/mounts/parser_test.go

backport of https://github.com/moby/moby/pull/39251 for 18.09
fixes https://github.com/docker/for-linux/issues/674 for 18.09
Errors were being ignored and always telling the user that the path
doesn't exist even if it was some other problem, such as a permission
error.

[18.09 backport] Fix error handling for bind mount spec parser.

---

internal/test/environment/environment.go

backport of https://github.com/moby/moby/pull/39215 for 18.09

[18.09 backport] Consider WINDOWS_BASE_IMAGE_TAG override when setting Windows base image for tests

---

Dockerfile

backport of https://github.com/moby/moby/pull/38524 for 18.09
Full diff: https://github.com/docker/docker-py/compare/8b246db271a85d6541dc458838627e89c683e42f...ac922192959870774ad8428344d9faa0555f7ba6 / https://github.com/docker/docker-py/compare/8b246db271a85d6541dc458838627e89c683e42f..ac922192959870774ad8428344d9faa0555f7ba6
Includes https://github.com/docker/docker-py/pull/2216, which fixes a test checking for an incorrect status code (found through https://github.com/moby/moby/pull/38487 - https://github.com/moby/moby/pull/38487#issuecomment-452484199)

[18.09 backport] Update docker-py to 3.7.0

---

Dockerfile
builder/remotecontext/detect.go
integration/build/build_test.go
vendor.conf
vendor/github.com/moby/buildkit/frontend/dockerfile/parser/parser.go

- bump buildkit 05766c5c21a1e528eeb1c3522b2f05493fe9ac47 (docker-18.09 branch)
- moby/buildkit#952 [18.09 backport] Have parser error on dockerfiles without instructions
- backport of moby/buildkit#771 Have parser error on dockerfiles without instructions
- https://github.com/moby/moby/pull/38487 Error on empty dockerfile
- first two commits (last commit (vendor bump) is replaced with the bump above)

[18.09 backport] fix panic on empty dockerfile

---

pkg/idtools/idtools.go
pkg/idtools/idtools_test.go

backport of https://github.com/moby/moby/pull/39288 for 18.09
Moby currently sorts uid and gid ranges in id maps. This causes subuid
and subgid files to be interpreted wrongly.
The subuid file
```
> cat /etc/subuid
jonas:100000:1000
jonas:1000:1
```
configures that the container uids 0-999 are mapped to the host uids
100000-100999 and uid 1000 in the container is mapped to uid 1000 on the
host. The expected uid_map is:
```
> docker run ubuntu cat /proc/self/uid_map
0     100000       1000
1000       1000          1
```
Moby currently sorts the ranges by the first id in the range. Therefore
with the subuid file above the uid 0 in the container is mapped to uid
100000 on host and the uids 1-1000 in container are mapped to the uids
1-1000 on the host. The resulting uid_map is:
```
> docker …
```

[18.09 backport] Stop sorting uid and gid ranges in id maps

---

vendor.conf
vendor/github.com/containerd/cgroups/cgroup.go

backport of https://github.com/moby/moby/pull/38965 for 18.09
full diff: https://github.com/containerd/cgroups/compare/dbea6f2bd41658b84b00417ceefa416b979cbf10...4994991857f9b0ae8dc439551e8bebdbb4bf66c1
brings in https://github.com/containerd/cgroups/pull/79 Return ErrCgroupDeleted when no subsystems
relates to https://github.com/containerd/containerd/issues/3133 Custom cgroup path does not work in containerd 1.2.5

[18.09 backport] update containerd/cgroups 4994991857f9b0ae8dc439551e8bebdbb4bf66c1

---

daemon/cluster/executor/container/container.go

backport of https://github.com/moby/moby/pull/39190
fixes https://github.com/moby/moby/issues/33538
Today `$ docker service create --limit-cpu` configures a containers `CpuPeriod` and `CpuQuota` variables, this commit switches this to configure a containers `NanoCpu` variable instead to try and fix moby/moby#33538 and provide support for limiting CPU on Windows Workloads.
This change makes  `$ docker service create --limit-cpu` the same as `$ docker run --cpu` as the later is supported on windows. https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-containers/resource-controls
The reason this change was required is because CPU Period is not supported on Windows today:
```
$ docker service create --limit-cpu "1.5" --name demo hello-world …
```

[18.09 backport] Switch swarmmode services to NanoCpu

---

builder/builder-next/adapters/containerimage/pull.go

back ports of https://github.com/moby/moby/pull/38246 and https://github.com/moby/moby/pull/39183 for 18.09
fixes https://github.com/moby/moby/issues/39182
addresses https://github.com/moby/buildkit/issues/720#issuecomment-440092509

[18.09 backport] builder: add workaround for gcr auth issue

---

daemon/logger/adapter.go

backport of https://github.com/moby/moby/pull/39038 for 18.09

[18.09 backport] Adds PartialLogMetadata to encode protobuf for logger plugins

---

daemon/container_operations.go
integration/service/network_test.go

backport of https://github.com/moby/moby/pull/39137 for 19.03
Fixes - https://github.com/docker/for-linux/issues/632
Signed-off-by: Arko Dasgupta <arko.dasgupta@docker.com>
Made sure the Networks context is manipulated in the scenario when a container attempts to attach to an a network it is already connected to
When attaching to a network in `findAndAttachNetwork` make sure you return with an error when that network is already part of `container.NetworkSettings.Networks`
Followed the same steps in the issue and made sure it is resolved

[19.03 backport] Handle the error case when a container reattaches to the same network

---

Dockerfile
Makefile
docs/contributing/set-up-dev-env.md
hack/ci/janky
hack/integration-cli-on-swarm/README.md
hack/make.sh
hack/make/test-integration-flaky
hack/test/unit

Backports of:
- https://github.com/moby/moby/pull/37879 go {build,test}: rm -i option, add go cache volume
- https://github.com/moby/moby/pull/37845 Allow to override the Makefile's `DOCKER_MOUNT` variable
- https://github.com/moby/moby/pull/38370 Update Dockerfile to skip source copy for speed up
- https://github.com/moby/moby/pull/38529 Makefile: make help: fix newline wrapping, and missing targets
- https://github.com/moby/moby/pull/38523 CI: Introduce flaky test finder
- https://github.com/moby/moby/pull/38693 hack: Have TIMEOUT take -test.count into account when testing for flakiness
- https://github.com/moby/moby/pull/38847 Enable buildkit for Makefile build target
```
git checkout -b 18.09_backport_makefile_and_test_changes ce-engine/18.09
git cherry-pick -s -S -x …
```

[18.09 backport] Makefile and test changes

---

daemon/archive.go
integration/container/copy_test.go
pkg/archive/archive_unix.go

backport of https://github.com/moby/moby/pull/39357 for 18.09
Another attempt at fixing https://github.com/moby/moby/issues/39348
Fixes https://github.com/moby/moby/issues/39348
Previous attempt at https://github.com/moby/moby/pull/39351
Before 7a7357d, archive.TarResourceRebase was being used to copy files
and folders from the container. That function splits the source path
into a dirname + basename pair to support copying a file:
if you wanted to tar `dir/file` it would tar from `dir` the file `file`
(as part of the IncludedFiles option).
However, that path splitting logic was kept for folders as well, which
resulted in weird inputs to archive.TarWithOptions:
if you wanted to tar `dir1/dir2` it would tar from `dir1` the directory
`dir2` (as part of IncludedFiles option).
Although it was …

[18.09 backport] Fix docker cp when container source path is /

---

api/server/middleware/debug.go
api/server/middleware/debug_test.go

Commit 77b8465d7e68ca102d7aae839c7b3fe0ecd28398 (https://github.com/moby/moby/pull/28720) added a secret update endpoint to allow updating labels on existing secrets. However, when implementing the endpoint, the DebugRequestMiddleware was not updated to scrub the Data field (as is being done when creating a secret).
When updating a secret (to set labels), the Data field should be either `nil` (not set), or contain the same value as the existing secret. In situations where the Data field is set, and the `dockerd` daemon is running with debugging enabled / log-level debug, the base64-encoded value of the secret is printed to the daemon logs.
The docker cli does not have a `docker secret update` command, but when using `docker stack deploy`, the docker cli sends the secret data both when …

[18.09 backport] DebugRequestMiddleware: unconditionally scrub data field

---

api/server/middleware/debug.go
api/server/middleware/debug_test.go

Commit 77b8465d7e68ca102d7aae839c7b3fe0ecd28398 (https://github.com/moby/moby/pull/28720) added a secret update endpoint to allow updating labels on existing secrets. However, when implementing the endpoint, the DebugRequestMiddleware was not updated to scrub the Data field (as is being done when creating a secret).
When updating a secret (to set labels), the Data field should be either `nil` (not set), or contain the same value as the existing secret. In situations where the Data field is set, and the `dockerd` daemon is running with debugging enabled / log-level debug, the base64-encoded value of the secret is printed to the daemon logs.
The docker cli does not have a `docker secret update` command, but when using `docker stack deploy`, the docker cli sends the secret data both when …

[19.03 backport] DebugRequestMiddleware: unconditionally scrub data field

---

hack/dockerfile/install/proxy.installer
vendor.conf
vendor/github.com/docker/libnetwork/controller.go
vendor/github.com/docker/libnetwork/drivers/bridge/setup_ip_tables.go
vendor/github.com/docker/libnetwork/drivers/overlay/ostweaks_linux.go
vendor/github.com/docker/libnetwork/drivers/windows/windows.go
vendor/github.com/docker/libnetwork/network.go
vendor/github.com/docker/libnetwork/osl/namespace_linux.go
vendor/github.com/docker/libnetwork/resolver_unix.go
vendor/github.com/docker/libnetwork/service_linux.go
vendor/github.com/docker/libnetwork/vendor.conf

full diff: https://github.com/docker/libnetwork/compare/e7933d41e7b206756115aa9df5e0599fc5169742...55685ba49593e67f5e1c8180539379b16736c25e
- docker/libnetwork#2382 Backporting PR 2069 to bump_18.09
- backport of https://github.com/docker/libnetwork#2069 Rolling back the port configs if failed to programIngress()
- docker/libnetwork#2363 [18.09] align dependencies with engine 18.09
- docker/libnetwork#2400 [18.09 backport] Fix TestValidRemoteDriver GetCapabilities errors
- docker/libnetwork#2391 [18.09 backport] Correctly clean up --config-only networks
- backport of docker/libnetwork#2373
- fixes moby/moby#35101
- docker/libnetwork#2392 [18.09 backport] remove gosimple - package is gone and it's not important

[18.09] bump libnetwork 55685ba49593e67f5e1c8180539379b16736c25e (18.09 branch)

---

daemon/container_operations.go

backport of https://github.com/moby/moby/pull/39589
fixes https://github.com/moby/moby/issues/39345
In situations where `container.NetworkSettings` was not nil, but
`container.NetworkSettings.Networks` was, a panic could occur:
```
2019-06-10 15:26:50.548309 I | http: panic serving @: assignment to entry in nil map
goroutine 1376 [running]:
net/http.(*conn).serve.func1(0xc4211068c0)
/usr/local/go/src/net/http/server.go:1726 +0xd2
panic(0x558939d7e1e0, 0x55893a0c4410)
/usr/local/go/src/runtime/panic.go:502 +0x22d
github.com/docker/docker/daemon.(*Daemon).updateNetworkSettings(0xc42090c5a0, 0xc420fb6fc0, 0x55893a101140, 0xc4210e0540, 0xc42112aa80, 0xc4217d77a0, 0x0)
/go/src/github.com/docker/docker/daemon/container_operations.go:275 +0x40e …
```

[19.03 backport] Prevent panic on network attach

---

daemon/graphdriver/copy/copy.go
daemon/graphdriver/copy/copy_cgo.go
daemon/graphdriver/copy/copy_nocgo.go
daemon/graphdriver/quota/projectquota.go
daemon/graphdriver/quota/projectquota_unsupported.go
daemon/graphdriver/quota/types.go
daemon/stats/collector_unix.go

This is a backport of
* https://github.com/moby/moby/pull/39327 allow dockerd builds without cgo
* https://github.com/moby/moby/pull/39644 projectquota: protect concurrent map access (ENGCORE-920)
to address
* https://github.com/moby/moby/issues/39643 Docker daemon crashes (again) with "fatal error: concurrent map read and map write"
Clean cherry-pick, no issues (https://github.com/moby/moby/pull/39327 is required solely for a clean cherry-pick)

[18.09 backport] projectquota: protect concurrent map access (ENGCORE-920)

---

Dockerfile
Dockerfile.e2e
Dockerfile.simple
Dockerfile.windows
Makefile
hack/ci/windows.ps1
hack/make.ps1

go1.11.12 (released 2019/07/08) includes fixes to the compiler and the linker.
See the Go 1.11.12 milestone on our issue tracker for details:
* https://github.com/golang/go/issues?q=milestone%3AGo1.11.12  
Full diff: https://github.com/golang/go/compare/go1.11.11...go1.11.12
* moby#37953 Dockerfile.e2e: simplify apk calls
* moby#39537 Dockerfile: Use APT_MIRROR for security.debian.org as well
* moby#39548 Dockerfile: use GO_VERSION build-arg for overriding Go version
* moby#39585 Dockerfile.windows: trim .0 from Go versions
* moby#39586 Windows: fix Golang version checks for GO_VERSION build-arg
* moby#39582 Pin Dockerfile to -stretch variant because it's bust'd

[18.09] Bump Go to  1.11.12

---

daemon/container_operations.go

backport of https://github.com/moby/moby/pull/39589
fixes https://github.com/moby/moby/issues/39345
In situations where `container.NetworkSettings` was not nil, but
`container.NetworkSettings.Networks` was, a panic could occur:
```
2019-06-10 15:26:50.548309 I | http: panic serving @: assignment to entry in nil map
goroutine 1376 [running]:
net/http.(*conn).serve.func1(0xc4211068c0)
/usr/local/go/src/net/http/server.go:1726 +0xd2
panic(0x558939d7e1e0, 0x55893a0c4410)
/usr/local/go/src/runtime/panic.go:502 +0x22d
github.com/docker/docker/daemon.(*Daemon).updateNetworkSettings(0xc42090c5a0, 0xc420fb6fc0, 0x55893a101140, 0xc4210e0540, 0xc42112aa80, 0xc4217d77a0, 0x0)
/go/src/github.com/docker/docker/daemon/container_operations.go:275 +0x40e …
```

[18.09 backport] Prevent panic on network attach

---

daemon/graphdriver/copy/copy.go
daemon/graphdriver/copy/copy_cgo.go
daemon/graphdriver/copy/copy_nocgo.go
daemon/graphdriver/quota/projectquota.go
daemon/graphdriver/quota/projectquota_unsupported.go
daemon/graphdriver/quota/types.go
daemon/stats/collector_unix.go

This is a backport of
* https://github.com/moby/moby/pull/39327 allow dockerd builds without cgo
* https://github.com/moby/moby/pull/39644 projectquota: protect concurrent map access (ENGCORE-920)
to address
* https://github.com/moby/moby/issues/39643 Docker daemon crashes (again) with "fatal error: concurrent map read and map write"
Clean cherry-pick, no issues (https://github.com/moby/moby/pull/39327 is required solely for a clean cherry-pick)

[19.03] backport projectquota: protect concurrent map access (ENGCORE-920)

---

Dockerfile
Dockerfile.e2e
Dockerfile.simple
Dockerfile.windows

backport of https://github.com/moby/moby/pull/39355 and https://github.com/moby/moby/pull/39474 for 19.03
go1.12.6 (released 2019/06/11) includes fixes to the compiler, the linker,
the go command, and the <code>crypto/x509</code>, <code>net/http</code>, and
<code>os</code> packages. See the<a href="https://github.com/golang/go/issues?q=milestone%3AGo1.12.6">Go 1.12.6 milestone</a> on our issue tracker for details.
https://github.com/golang/go/compare/go1.12.5...go1.12.6
go1.12.7 (released 2019/07/08) includes fixes to cgo, the compiler, and the
linker. See the Go 1.12.7 milestone on our issue tracker for details:
https://github.com/golang/go/issues?q=milestone%3AGo1.12.7
full diff: https://github.com/golang/go/compare/go1.12.6...go1.12.7

[19.03 backport] Bump Golang 1.12.7

---

docs/rootless.md
hack/dockerfile/install/rootlesskit.installer

backport of https://github.com/moby/moby/pull/39493

[19.03 backport] rootless: allow exposing dockerd TCP socket easily

---

Dockerfile
Dockerfile.e2e
Dockerfile.simple
Dockerfile.windows
Makefile
TESTING.md
hack/ci/windows.ps1
hack/make.ps1

Backports of:
- https://github.com/moby/moby/pull/39537 Dockerfile: Use APT_MIRROR for security.debian.org as well
- https://github.com/moby/moby/pull/39548 Dockerfile: use GO_VERSION build-arg for overriding Go version
- https://github.com/moby/moby/pull/39582 Pin Dockerfile to -stretch variant because it's bust'd
- closes https://github.com/moby/moby/pull/39581

[19.03 backport] use GO_VERSION and pin to debian stretch

---

builder/dockerfile/copy.go
hack/make.ps1
integration/build/build_test.go
integration/build/testdata/Dockerfile.TestBuildMultiStageCopy

backport of:
- https://github.com/moby/moby/pull/39698 make.ps1: `Run-IntegrationTests()`: set working directory for test suite
- https://github.com/moby/moby/pull/39695 Builder: fix `COPY --from` to non-existing directory on Windows
fixes docker/for-win#4349
built on top of https://github.com/moby/moby/pull/39698
This fixes a regression introduced in 6d87f19142f86b8fee75af721b583a306202f228 (https://github.com/moby/moby/pull/38599),
causing `COPY --from` to fail if the target directory does not exist:
```Dockerfile
FROM mcr.microsoft.com/windows/servercore:ltsc2019 as s1
RUN echo "Hello World" > /hello
FROM mcr.microsoft.com/windows/servercore:ltsc2019
COPY --from=s1 /hello /hello/another/world
```
Would produce an error:
```
Step 4/4 : COPY --from=s1 /hello /hello/another/world
failed …
```

[19.03 backport] Builder: fix "COPY --from" to non-existing directory on Windows [ENGCORE-935]

---

pkg/chrootarchive/chroot_unix.go

backport of https://github.com/moby/moby/pull/39462
3029e765e241ea2b5249868705dbf9095bc4d529 (https://github.com/moby/moby/pull/39292) broke compilation on
non-Linux/Windows systems.
This change fixes that.
Fixes https://github.com/moby/moby/issues/39437

[18.09 backport] Add realChroot for non linux/windows

---

pkg/chrootarchive/chroot_unix.go

backport of https://github.com/moby/moby/pull/39462
3029e765e241ea2b5249868705dbf9095bc4d529 (https://github.com/moby/moby/pull/39292) broke compilation on
non-Linux/Windows systems.
This change fixes that.
Fixes https://github.com/moby/moby/issues/39437

[19.03 backport] Add realChroot for non linux/windows

---

daemon/daemon.go

backport of https://github.com/moby/moby/pull/39703 for 19.03
Signed-off-by: Deep Debroy <ddebroy@docker.com>
(cherry picked from commit 4d5b6260bc595d5d9787c67ae887e83432911380)
Address a regression during daemon startup introduced in https://github.com/moby/moby/pull/38931.
fixes https://github.com/moby/moby/issues/39623
fixes https://github.com/docker/for-win/issues/4463
fixes https://github.com/microsoft/navcontainerhelper/issues/548
Added (back) proper handling of NotFound err
Start a container in Windows like: 
```
docker run -d --restart always --name testcontainer --network nat -p 8080:80 mcr.microsoft.com/windows/servercore:ltsc2019 ping -t 127.0.0.1
```
and …

[19.03 backport] Fix regression in handling of NotFound err during startup ENGCORE-929

---

vendor.conf
vendor/github.com/docker/swarmkit/manager/controlapi/node.go

full diff: https://github.com/docker/swarmkit/compare/961ec3a56b7b6c311a2137b6a398f9d778fba94b...4fb9e961aba635f0240a140e89ece6d6c2082585
included:
- docker/swarmkit#2873 [19.03 backport] Only update non-terminal tasks on node removal
- backport of docker/swarmkit#2867 Only update non-terminal tasks on node removal

[19.03] bump swarmkit to 4fb9e961aba635f0240a140e89ece6d6c2082585 (bump_v19.03)

---

vendor.conf
vendor/github.com/docker/swarmkit/manager/controlapi/node.go

full diff: https://github.com/docker/swarmkit/compare/19e791fd6dc76e8e894cbc99b77f946b7d00ebb9...142a73731c850daf24d32001aa2358b6ffe36eab
included:
- docker/swarmkit#2872 [19.03 backport] Only update non-terminal tasks on node removal
- backport of docker/swarmkit#2867 Only update non-terminal tasks on node removal

[18.09] bump swarmkit to 142a73731c850daf24d32001aa2358b6ffe36eab (bump_v18.09)

---

daemon/cluster/cluster.go
daemon/cluster/swarm.go

backport of https://github.com/moby/moby/pull/39346
follow up to https://github.com/moby/moby/pull/39306
There are a few more places, apparently, that List operations against
Swarm exist, besides just in the List methods. This increases the max
received message size in those places.

[18.09 backport] Fix more grpc list message sizes

---

daemon/cluster/cluster.go
daemon/cluster/swarm.go

backport of https://github.com/moby/moby/pull/39346
follow up to https://github.com/moby/moby/pull/39306
There are a few more places, apparently, that List operations against
Swarm exist, besides just in the List methods. This increases the max
received message size in those places.
- Fix "grpc: received message larger than max" errors. [moby/moby#39306](https://github.com/moby/moby/pull/39306)

[19.03 backport] Fix more grpc list message sizes

---

pkg/plugins/client_test.go

backport of https://github.com/moby/moby/pull/39168
DeadlineExceeded now implements a TimeOut() function,
since https://github.com/golang/go/commit/dc4427f3727804ded270bc6a7a8066ccb3c151d0
Check for this interface, to prevent possibly incorrect failures;
```
00:16:41 --- FAIL: TestClientWithRequestTimeout (0.00s)
00:16:41     client_test.go:259: assertion failed:
00:16:41         --- context.DeadlineExceeded
00:16:41         +++ err
00:16:41         :
00:16:41         	-: context.deadlineExceededError{}
00:16:41         	+: &net.OpError{Op: "dial", Net: "tcp", Addr: s"127.0.0.1:49294", Err: &poll.TimeoutError{}}
00:16:41
```

[19.03 backport] Harden TestClientWithRequestTimeout

---

pkg/plugins/client_test.go

backport of https://github.com/moby/moby/pull/39168
DeadlineExceeded now implements a TimeOut() function,
since https://github.com/golang/go/commit/dc4427f3727804ded270bc6a7a8066ccb3c151d0
Check for this interface, to prevent possibly incorrect failures;
```
00:16:41 --- FAIL: TestClientWithRequestTimeout (0.00s)
00:16:41     client_test.go:259: assertion failed:
00:16:41         --- context.DeadlineExceeded
00:16:41         +++ err
00:16:41         :
00:16:41         	-: context.deadlineExceededError{}
00:16:41         	+: &net.OpError{Op: "dial", Net: "tcp", Addr: s"127.0.0.1:49294", Err: &poll.TimeoutError{}}
00:16:41
```

[18.09 backport] Harden TestClientWithRequestTimeout

---

Dockerfile
Dockerfile.e2e
Dockerfile.simple
Dockerfile.windows
opts/hosts_test.go

go1.11.13 (released 2019/08/13) includes security fixes to the net/http and net/url packages.
See the Go 1.11.13 milestone on our issue tracker for details:
https://github.com/golang/go/issues?q=milestone%3AGo1.11.13
- net/http: Denial of Service vulnerabilities in the HTTP/2 implementation
net/http and golang.org/x/net/http2 servers that accept direct connections from untrusted
clients could be remotely made to allocate an unlimited amount of memory, until the program
crashes. Servers will now close connections if the send queue accumulates too many control
messages.
The issues are CVE-2019-9512 and CVE-2019-9514, and Go issue golang.org/issue/33606.
Thanks to Jonathan Looney from Netflix for discovering and reporting these issues.
This is also fixed in version …

[18.09] Bump golang 1.11.13 (CVE-2019-9512, CVE-2019-9514)

---

Dockerfile
Dockerfile.e2e
Dockerfile.simple
Dockerfile.windows
TESTING.md
opts/hosts_test.go

backport of https://github.com/moby/moby/pull/39738 for 19.03
go1.12.8 (released 2019/08/13) includes security fixes to the net/http and net/url packages.
See the Go 1.12.8 milestone on our issue tracker for details:
https://github.com/golang/go/issues?q=milestone%3AGo1.12.8
- net/http: Denial of Service vulnerabilities in the HTTP/2 implementation
net/http and golang.org/x/net/http2 servers that accept direct connections from untrusted
clients could be remotely made to allocate an unlimited amount of memory, until the program
crashes. Servers will now close connections if the send queue accumulates too many control
messages.
The issues are CVE-2019-9512 and CVE-2019-9514, and Go issue golang.org/issue/33606.
Thanks to Jonathan Looney from Netflix for discovering and reporting these …

[19.03 backport] Bump golang 1.12.8 (CVE-2019-9512, CVE-2019-9514)

---

daemon/kill.go
integration-cli/docker_cli_health_test.go
integration/container/health_test.go

https://github.com/moby/moby/pull/39454
Just to summarize, the concern in this backport  is the risk of leaking health monitor routines. Those routines need to be explicitly stopped.
The only other place where we explicitly  stop those threads , is when we get an event from containerd, so as long as those events are delivered, we should be good.
Note, this is the change that introduced the original problem and you can see how the health monitor was explicitly stopped, (in addition to the containerd event)
https://github.com/moby/moby/pull/35501
Had a chat with @crosbymichael and @thaJeztah we decided to go ahead with the port , unless someone else has any concerns
**- A picture of a cute animal …

[18.09 backport] do not stop health check before sending signal

---

daemon/kill.go
integration-cli/docker_cli_health_test.go
integration/container/health_test.go

https://github.com/moby/moby/pull/39454
Just to summarize, the concern in this backport  is the risk of leaking health monitor routines. Those routines need to be explicitly stopped.
The only other place where we explicitly  stop those threads , is when we get an event from containerd, so as long as those events are delivered, we should be good.
Note, this is the change that introduced the original problem and you can see how the health monitor was explicitly stopped, (in addition to the containerd event)
https://github.com/moby/moby/pull/35501
Had a chat with @crosbymichael and @thaJeztah we decided to go ahead with the port , unless someone else has any concerns
**- A picture of a cute animal …

[19.03 backport] do not stop health check before sending signal

---

builder/builder-next/adapters/snapshot/snapshot.go

backport https://github.com/moby/moby/pull/39754
fixes https://github.com/moby/buildkit/issues/1134
buildkit side protection in https://github.com/moby/buildkit/pull/1137
(cherry picked from commit 9ea2cf320ad2687a51aea1ed849f86f465cbc1d9)

[19.03] builder-next: avoid double unmounting mountable

---

pkg/loopback/ioctl.go

_Backport of PR moby/moby#39801_
---
The `ioctl` interface for the `LOOP_CTL_GET_FREE` request on
`/dev/loop-control` is a little different from what `unix.IoctlGetInt`
expects: the first index is the returned status in `r1`, not an `int`
pointer as the first parameter.
Unfortunately we have to go a little lower level to get the appropriate
loop device index out, using `unix.Syscall` directly to read from
`r1`. Internally, the index is returned as a signed integer to match the
internal `ioctl` expectations of interpreting a negative signed integer
as an error at the userspace ABI boundary, so the direct interface of
`ioctlLoopCtlGetFree` can remain as-is.
[@kolyshkin: it still worked before this fix because of
/dev scan fallback in ioctlLoopCtlGetFree()]

[19.03 backport] Use correct `LOOP_CTL_GET_FREE` API in `pkg/loopback`

---

integration/network/service_test.go

Backport of https://github.com/moby/moby/pull/39453
Ref: https://github.com/moby/moby/issues/39426
This is a common flaky test that I have seen on multiple PRs.  It is not
consistent and should be skipped until it is fixed to be robust.  A
simple fix for the swarm tests is not easy as they all poll and have 1
billion timeouts in all the tests so a skip is valid here.

[19.03 backport] Skip TestServiceRemoveKeepsIngressNetwork

---

integration-cli/docker_api_swarm_test.go
integration-cli/docker_cli_swarm_test.go
internal/test/daemon/node.go

- _Partial_ backport of https://github.com/moby/moby/pull/39531 integration-cli: fix swarm tests flakiness
- **skipped second commit (SwarmKit bump) as that requires backport to the SwarmKit bump_v19.03 branch**
- addresses https://github.com/moby/moby/issues/36903 Flaky test: TestAPISwarmServicesCreate
- addresses https://github.com/moby/moby/issues/34988 Flaky test: TestAPISwarmRaftQuorum
- addresses https://github.com/moby/moby/issues/37132 Flaky test: TestServicePlugin, TestCreateServiceSecretFileMode
- addresses https://github.com/moby/moby/issues/32673 Flaky test: TestAPISwarmLeaderElection
- addresses https://github.com/moby/moby/issues/28240 Flaky test: DockerSwarmSuite.TestSwarmRotateUnlockKey
- addresses https://github.com/moby/moby/issues/38885 Flaky test: …

[19.03 backport] integration-cli: fix swarm tests flakiness

---

builder/builder-next/adapters/containerimage/pull.go

backport of https://github.com/moby/moby/pull/39543
fixes https://github.com/moby/buildkit/issues/1079
causes panic on armv7

[19.03 backport] atomic: patch 64bit alignment on 32bit systems

---

daemon/daemon_unix.go

backport of https://github.com/moby/moby/pull/39496
While investigating a test failure, I found this in the logs:
```
time="2019-07-04T15:06:32.622506760Z" level=warning msg="Error while setting daemon root propagation, this is not generally critical but may cause some functionality to not work or fallback to less desirable behavior" dir=/go/src/github.com/docker/docker/bundles/test-integration/d1285b8250308/root error="error writing file to signal mount cleanup on shutdown: open /tmp/dxr/d1285b8250308/unmount-on-shutdown: no such file or directory"
```
This path is generated from the daemon's exec-root, which appears to not
exist yet. This change just makes sure it exists before we try to write
a file.

[19.03 backport] Ensure parent dir exists for mount cleanup file

---

Dockerfile
Dockerfile.e2e
Dockerfile.simple
Dockerfile.windows

backport of https://github.com/moby/moby/pull/39755
go1.12.9 (released 2019/08/15) includes fixes to the linker,
and the <code>os</code> and <code>math/big</code> packages.
See the <a href="https://github.com/golang/go/issues?q=milestone%3AGo1.12.9+label%3ACherryPickApproved">Go
1.12.9 milestone</a> on our issue tracker for details.
Full diff https://github.com/golang/go/compare/go1.12.8...go1.12.9
bump golang 1.12.9

[19.03 backport] Bump Golang 1.12.9

---

integration-cli/docker_cli_search_test.go

back port of https://github.com/moby/moby/pull/39258

[19.03 backport] Revert "Remove TestSearchCmdOptions test"

---

errdefs/http_helpers.go
integration/build/build_test.go
integration/image/pull_test.go

backport of https://github.com/moby/moby/pull/39527
Relates to https://github.com/docker/docker-py/pull/2382#issue-297611082
In situations where the containerd error is consumed directly
and not received over gRPC, errors were not translated.
Before we handled containerd errors, using an invalid platform produced a 500 status:
```bash
curl -v \
-X POST \
--unix-socket /var/run/docker.sock \
"http://localhost:2375/v1.40/images/create?fromImage=hello-world&platform=foobar&tag=latest" \
-H "Content-Type: application/json"
```
```
* Connected to localhost (docker.sock) port 80 (#0)
> POST /v1.40/images/create?fromImage=hello-world&platform=foobar&tag=latest HTTP/1.1
> Host: localhost:2375
> User-Agent: curl/7.54.0
> Accept: */*
> Content-Type: application/json
>
< HTTP/1.1 500 Internal Server …
```

[19.03 backport] Fix error handling of incorrect --platform values

---

Jenkinsfile

This will help [reduce PR check times](https://github.com/moby/moby/issues/39651).
Clean cherry-pick of c18f793 (to avoid conflicts), 039eb05, and e653943:
```
$ git cherry-pick -s -x c18f793f40c8692a06a73a8ed1b14b05091964f9
[skip-rs1 ca22ec44ba] Jenkinsfile: shorten stage names for consistency and to fit Jenkins UI
Author: Sebastiaan van Stijn <github@gone.nl>
Date: Tue Sep 10 09:46:19 2019 +0200
1 file changed, 21 insertions(+), 21 deletions(-)
$ git cherry-pick -s -x 039eb05ac87d52fe0b268c090f137eaa14754eed
[skip-rs1 36fc8f5809] skip win-RS1 on PRs unless the checkbox is checked
Date: Tue Sep 10 23:37:09 2019 +0000
1 file changed, 6 insertions(+), 2 deletions(-)
$ git cherry-pick -s -x e653943e8befaff83d6ace9b6f943f0cc8027ae4
[skip-rs1 a18eea2702] run integration-cli stages on s390x …
```

[19.03] skip win-RS1 on PRs

---

daemon/daemon_unix.go
integration/container/create_test.go

backport of https://github.com/moby/moby/pull/39852 to fix the regression in 19.03
fixes https://github.com/moby/moby/issues/39823
fixes https://github.com/docker/for-mac/issues/3871
Trying to link to a non-existing container is not valid, and should return an
"invalid parameter" (400) error. Returning a "not found" error in this situation
would make the client report the container's image could not be found.

[19.03 backport] Return "invalid parameter" when linking to non-existing container

---

vendor.conf
vendor/github.com/docker/swarmkit/manager/manager.go

full diff: https://github.com/docker/swarmkit/compare/bbe341867eae1615faf8a702ec05bfe986e73e06...f35d9100f2c6ac810cc8d7de6e8f93dcc7a42d29
- docker/swarmkit#2891 [19.03 backport] Remove hardcoded IPAM config subnet value for ingress network
- backport of docker/swarmkit#2890 Remove hardcoded IPAM config subnet value for ingress network
- fixes [ENGORC-2651] Specifying --default-addr-pool for docker swarm init is not picked up by ingress network

[19.03] bump swarmkit to f35d9100f2c6ac810cc8d7de6e8f93dcc7a42d29

---

Jenkinsfile

Clean cherry-pick of f470698:
```
$ git cherry-pick -s -x f470698c2c10c2382080fab34f83088450fabdd6
[clean 4b5c535be9] Jenkinsfile: ensure all containers are cleaned up
Author: Tibor Vass <tibor@docker.com>
Date: Wed Sep 18 21:47:58 2019 +0000
1 file changed, 2 insertions(+)
```

[19.03] Jenkinsfile: ensure all containers are cleaned up

---

distribution/pull_v2.go
distribution/push_v2.go
distribution/registry.go

Clean cherry-pick of https://github.com/moby/moby/pull/39736

[19.03 backport] distribution: modify warning logic when pulling v2 schema1 manifests

---

daemon/monitor.go

backport of https://github.com/moby/moby/pull/39434
fixes #39427
This always sends the exec exit events even when the exec fails to find
the binary.  A standard 127 exit status is sent in this situation.

[19.03 backport] Send exec exit event on failures

---

vendor.conf
vendor/github.com/docker/swarmkit/manager/manager.go

Alternative to https://github.com/docker/engine/pull/374
This reverts commit 02465c9f9da4064211d0f7e56a8c93a567589713 (https://github.com/docker/engine/pull/369)
to fix CI being red after merging https://github.com/docker/engine/pull/369 (effectively a backport of https://github.com/moby/moby/pull/39953) without making changes to the test (done in https://github.com/moby/moby/pull/39966)

[19.03] Revert "bump swarmkit to f35d9100f2c6ac810cc8d7de6e8f93dcc7a42d29"

---

daemon/images/image_delete.go

backport of https://github.com/moby/moby/pull/39749
fixes https://github.com/moby/moby/issues/39739

[19.03 backport] fix docker rmi stucking

---

integration/network/service_test.go

Backport of https://github.com/moby/moby/pull/39453
Ref: https://github.com/moby/moby/issues/39426
This is a common flaky test that I have seen on multiple PRs.  It is not
consistent and should be skipped until it is fixed to be robust.  A
simple fix for the swarm tests is not easy as they all poll and have 1
billion timeouts in all the tests so a skip is valid here.

[18.09 backport] Skip TestServiceRemoveKeepsIngressNetwork

---

integration-cli/docker_cli_search_test.go

backport of https://github.com/moby/moby/pull/39258

[18.09 backport] Revert "Remove TestSearchCmdOptions test"

---

daemon/images/image_delete.go

backport of https://github.com/moby/moby/pull/39749
fixes https://github.com/moby/moby/issues/39739

[18.09 backport] fix docker rmi stucking

---

builder/builder-next/adapters/containerimage/pull.go

backport of https://github.com/moby/moby/pull/39543
fixes https://github.com/moby/buildkit/issues/1079
causes panic on armv7

[18.09 backport] atomic: patch 64bit alignment on 32bit systems

---

profiles/seccomp/default.json
profiles/seccomp/seccomp_default.go

backport of https://github.com/moby/moby/pull/39824
addresses [ENGCORE-976]
fixes [ENGCORE-980]
[ENGCORE-976]: https://docker.atlassian.net/browse/ENGCORE-976
[ENGCORE-980]: https://docker.atlassian.net/browse/ENGCORE-980

[18.09 backport] Add sigprocmask to default seccomp profile (ENGCORE-980)

---

daemon/daemon_unix.go

backport of https://github.com/moby/moby/pull/39496
While investigating a test failure, I found this in the logs:
```
time="2019-07-04T15:06:32.622506760Z" level=warning msg="Error while setting daemon root propagation, this is not generally critical but may cause some functionality to not work or fallback to less desirable behavior" dir=/go/src/github.com/docker/docker/bundles/test-integration/d1285b8250308/root error="error writing file to signal mount cleanup on shutdown: open /tmp/dxr/d1285b8250308/unmount-on-shutdown: no such file or directory"
```
This path is generated from the daemon's exec-root, which appears to not
exist yet. This change just makes sure it exists before we try to write
a file.

[18.09 backport] Ensure parent dir exists for mount cleanup file

---

libcontainerd/client_daemon.go

backport https://github.com/moby/moby/pull/39513
This prevents restarting event processing in a tight loop.
You can see this with the following steps:
```terminal
$ containerd &
$ dockerd --containerd=/run/containerd/containerd.sock &
$ pkill -9 containerd
```
At this point you will be spammed with logs such as:
```
ERRO[2019-07-12T22:29:37.318761400Z] failed to get event                           error="rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial unix /run/containerd/containerd.sock: connect: connection refused\"" module=libcontainerd namespace=plugins.moby
```
Without this change you can quickly end up with gigabytes of log data.

[18.09 backport] Sleep before restarting event processing

---

daemon/graphdriver/overlay2/check.go
daemon/graphdriver/overlay2/overlay.go

backport of https://github.com/moby/moby/pull/38968 and https://github.com/moby/moby/pull/39780 for 19.03
When mounting overlays which have children, enforce that
the mount is always performed as read only. Newer versions
of the kernel return a device busy error when a lower directory
is in use as an upper directory in another overlay mount.
Adds committed file to indicate when an overlay is being used
as a parent, ensuring it will no longer be mounted with an
upper directory.
Related to [kernel@146d62e5a586](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=146d62e5a5867fbf84490d82455718bfb10fe824)

[18.09 backport] Fix overlay2 busy error on mount

---

pkg/loopback/ioctl.go

_backport of moby/moby#39801_
----
The `ioctl` interface for the `LOOP_CTL_GET_FREE` request on
`/dev/loop-control` is a little different from what `unix.IoctlGetInt`
expects: the first index is the returned status in `r1`, not an `int`
pointer as the first parameter.
Unfortunately we have to go a little lower level to get the appropriate
loop device index out, using `unix.Syscall` directly to read from
`r1`. Internally, the index is returned as a signed integer to match the
internal `ioctl` expectations of interpreting a negative signed integer
as an error at the userspace ABI boundary, so the direct interface of
`ioctlLoopCtlGetFree` can remain as-is.
[@kolyshkin: it still worked before this fix because of
/dev scan fallback in ioctlLoopCtlGetFree()]

[18.09 backport] Use correct `LOOP_CTL_GET_FREE` API in `pkg/loopback`

---

container/container.go
container/stream/streams.go
daemon/exec/exec.go
daemon/monitor.go
integration-cli/docker_cli_exec_test.go
libcontainerd/remote/client.go

backport of https://github.com/moby/moby/pull/39383 and https://github.com/moby/moby/pull/39677
fixes https://github.com/moby/moby/issues/39326
This is the second part to https://github.com/containerd/containerd/pull/3361 and will help process delete not block forever when the process exists but the I/O was inherited by a subprocess that lives on.
Reported by govet linter:
```
daemon/monitor.go:57:9: lostcancel: the cancel function returned by context.WithTimeout should be called, not discarded, to avoid a context leak (govet)
ctx, _ := context.WithTimeout(context.Background(), 2*time.Second)
^
daemon/monitor.go:128:9: lostcancel: the cancel function returned by context.WithTimeout should be called, not discarded, to avoid a context leak (govet)
ctx, _ := …
```

[19.03 backport] Handle blocked I/O of exec'd processes

---

integration/network/ipvlan/ipvlan_test.go

backport of https://github.com/moby/moby/pull/39358 for 18.09

[18.09 backport] For ipvlan tests check that the ipvlan module is enabled

---

daemon/monitor.go

backport of https://github.com/moby/moby/pull/39434
minor conflict because https://github.com/moby/moby/commit/85ad4b16c11425eaeace532bfce9029cfdcabe4b (https://github.com/moby/moby/pull/38541) is not in 18.09, and which moved the types from `libcontainerd` to `libcontainerdtypes`
fixes #39427
This always sends the exec exit events even when the exec fails to find
the binary.  A standard 127 exit status is sent in this situation.

[18.09 backport] Send exec exit event on failures

---

client/request.go

backport of https://github.com/moby/moby/pull/39588
addresses [DESKTOP-1286]
Improve the readability of the connection error displayed to the user on
Windows when running docker commands fails by checking if the client is
privileged. If so then display the actual error wrapped in a generic
error "This error may indicate that the docker daemon is not running."
If not that display the actual error wrapped in a more specific error:
"In the default daemon configuration on Windows, the docker client must
be run with elevated privileges to connect."
[DESKTOP-1286]: https://docker.atlassian.net/browse/DESKTOP-1286

[18.09 backport] Improve readability of Windows connect error

---

client/client.go
client/client_deprecated.go
client/options.go

This backports https://github.com/moby/moby/pull/38909 (Fix client version not being pinned when set) to the 18.09 branch.
When backporting, I noticed that there were some refactorings and cleanups in this area, which I decided to include here as well;
note that those are **_not_ strictly needed for the actual fix**; the fix is quite small, and could easily be modified to work on the 18.09
branch, but in light of future backports and maintenance, I thought it'd be good to include those refactors.
If this is a concern, I'm happy to create a modified patch and _only_ backport the fix.
Included in this PR:
- https://github.com/moby/moby/pull/38125 Add an op func to override Client.scheme
- ~https://github.com/moby/moby/pull/38486 Remove use of deprecated client.NewEnvClient()~
- …

[18.09 backport] Fix client version not being pinned when set, and some refactoring

---

daemon/container_operations.go
integration/service/network_test.go

backport of https://github.com/moby/moby/pull/39137 for 18.09
fixes https://github.com/docker/for-linux/issues/632
Signed-off-by: Arko Dasgupta <arko.dasgupta@docker.com>
Made sure the Networks context is manipulated in the scenario when a container attempts to attach to an a network it is already connected to
When attaching to a network in `findAndAttachNetwork` make sure you return with an error when that network is already part of `container.NetworkSettings.Networks`
Followed the same steps in the issue and made sure it is resolved

[18.09 backport] Handle the error case when a container reattaches to the same network

---

vendor.conf
vendor/github.com/containerd/go-runc/command_linux.go
vendor/github.com/containerd/go-runc/runc.go
vendor/github.com/moby/buildkit/executor/runcexecutor/executor.go
vendor/github.com/moby/buildkit/go.mod
vendor/github.com/moby/buildkit/session/sshforward/copy.go
vendor/github.com/moby/buildkit/session/sshforward/ssh.go
vendor/github.com/moby/buildkit/solver/edge.go
vendor/github.com/moby/buildkit/solver/internal/pipe/pipe.go
vendor/github.com/moby/buildkit/solver/llbsolver/bridge.go
vendor/github.com/moby/buildkit/source/http/httpsource.go
vendor/github.com/tonistiigi/fsutil/copy/copy.go
vendor/github.com/tonistiigi/fsutil/copy/copy_darwin.go
vendor/github.com/tonistiigi/fsutil/copy/copy_linux.go
vendor/github.com/tonistiigi/fsutil/copy/copy_unix.go
vendor/github.com/tonistiigi/fsutil/copy/copy_windows.go
vendor/github.com/tonistiigi/fsutil/stat.go

Fix socket handling https://github.com/moby/buildkit/pull/1144
session: release forwarded ssh socket connection per connection https://github.com/moby/buildkit/pull/1150
llbsolver: fix error on multiple cache importers https://github.com/moby/buildkit/pull/1156
http: Handle missing but unambiguous ETags in response https://github.com/moby/buildkit/pull/1159
solver: fix pipe signaling on incoming updates https://github.com/moby/buildkit/pull/1166
vendor: update go-runc to e029b79d https://github.com/moby/buildkit/pull/1168
https://github.com/moby/buildkit/pull/1178

[19.03] vendor: update buildkit for 19.03

---

pkg/mount/mounter_unsupported.go
pkg/mount/unmount_unsupported.go

Backport of https://github.com/moby/moby/pull/38372 to 18.09. Clean cherry-pick.
Needed for https://github.com/docker/cli/pull/2100
Original description follows.
---
Fix unmount redeclaration on darwin in github.com/docker/docker/pkg/mount

[18.09 backport] Fix unmount redeclaration on darwin

---

daemon/logger/loggerutils/logfile.go

Backport of moby#39969 to 19.03; clean cherry-pick, no issues. Original description follows.
---
In case jsonlogfile is used with `max-file=1` and `max-size` set,
the log rotation is not performed; instead, the log file is closed
and re-opened with `O_TRUNC`.
This situation is not handled by the log reader in follow mode,
leading to an issue of log reader being stuck forever.
This situation (file close/reopen) could be handled in `waitRead()`,
but fsnotify library chose to not listen to or deliver this event
(`IN_CLOSE_WRITE` in inotify lingo) as it's not portable,
see https://github.com/fsnotify/fsnotify/pull/252.
So, we have to handle this by checking the file size upon receiving
`io.EOF` from the log reader, and comparing the size with the one received
earlier. In case the new size is …

[19.03 backport] logger: fix follow logs for max-file=1

---

integration/network/service_test.go

Backports of 
- https://github.com/moby/moby/pull/37836 TestServiceWithDefaultAddressPoolInit
- https://github.com/moby/moby/pull/39671 Fix flaky TestServiceWithDefaultAddressPoolInit
- fixes https://github.com/moby/moby/issues/38514

[19.03 backport] Fix flaky TestServiceWithDefaultAddressPoolInit

---

libcontainerd/local/local_windows.go

backport of https://github.com/moby/moby/pull/39255
Trying to start a container that is already running is not an error condition, so a `304 Not Modified` should be returned instead of a `409 Conflict`.
relates to https://github.com/moby/moby/pull/39253
```Markdown
* Windows: fix API status code when starting an already running container. Trying to start a container that is already running is not an error condition, so a `304 Not Modified` should be returned instead of a `409 Conflict`.
```

[19.03 backport] Windows: fix error-type for starting a running container

---

vendor.conf
vendor/github.com/gorilla/mux/mux.go
vendor/github.com/gorilla/mux/regexp.go
vendor/github.com/gorilla/mux/route.go

backport of https://github.com/moby/moby/pull/39381 for 19.03
cli bump is in https://github.com/docker/cli/pull/1958
full diff: https://github.com/gorilla/mux/compare/v1.7.0...v1.7.2
includes:
- gorilla/mux#457 adding Router.Name to create new Route
- gorilla/mux#447 host:port matching does not require a :port to be specified

[19.03 backport] bump gorilla/mux v1.7.2

---

hack/dockerfile/install/proxy.installer
vendor.conf
vendor/github.com/docker/libnetwork/driverapi/driverapi.go
vendor/github.com/docker/libnetwork/drivers/bridge/setup_ip_forwarding.go
vendor/github.com/docker/libnetwork/drivers/windows/windows.go
vendor/github.com/docker/libnetwork/drivers/windows/windows_store.go
vendor/github.com/docker/libnetwork/network.go

backport of https://github.com/moby/moby/pull/39967
full diff: https://github.com/docker/libnetwork/compare/92d1fbe1eb0883cf11d283cea8e658275146411d...96bcc0dae898308ed659c5095526788a602f4726
- docker/libnetwork#2429 Updating IPAM config with results from HNS create network call
- addresses moby/moby#38358
- docker/libnetwork#2450 Always configure iptables forward policy
- related to moby/moby#14041 and docker/libnetwork#1526

[19.03 backport] bump libnetwork to 96bcc0dae898308ed659c5095526788a602f4726

---

daemon/logger/loggerutils/logfile.go

Backport of https://github.com/moby/moby/pull/39969 to 18.09; clean cherry-pick, no issues. Original description follows.
----
In case jsonlogfile is used with `max-file=1` and `max-size` set,
the log rotation is not performed; instead, the log file is closed
and re-opened with `O_TRUNC`.
This situation is not handled by the log reader in follow mode,
leading to an issue of log reader being stuck forever.
This situation (file close/reopen) could be handled in `waitRead()`,
but fsnotify library chose to not listen to or deliver this event
(`IN_CLOSE_WRITE` in inotify lingo) as it's not portable,
see https://github.com/fsnotify/fsnotify/pull/252.
So, we have to handle this by checking the file size upon receiving
`io.EOF` from the log reader, and comparing the size with the one received …

[18.09 backport] logger: fix follow logs for max-file=1

---

pkg/namesgenerator/names-generator.go

backport of https://github.com/moby/moby/pull/39982
fixes https://github.com/moby/moby/issues/39981

[19.03 backport] Remove minsky and stallman

---

pkg/namesgenerator/names-generator.go

backport of https://github.com/moby/moby/pull/39982
fixes https://github.com/moby/moby/issues/39981

[18.09 backport] Remove minsky and stallman

---

hack/dockerfile/install/containerd.installer
hack/dockerfile/install/runc.installer
vendor.conf
vendor/github.com/opencontainers/runc/libcontainer/README.md
vendor/github.com/opencontainers/runc/libcontainer/cgroups/utils.go
vendor/github.com/opencontainers/runc/libcontainer/configs/blkio_device.go
vendor/github.com/opencontainers/runc/libcontainer/configs/cgroup_linux.go
vendor/github.com/opencontainers/runc/libcontainer/configs/cgroup_unsupported.go
vendor/github.com/opencontainers/runc/libcontainer/devices/devices.go
vendor/github.com/opencontainers/runc/libcontainer/nsenter/nsenter_unsupported.go
vendor/github.com/opencontainers/runc/libcontainer/nsenter/nsexec.c
vendor/github.com/opencontainers/runc/libcontainer/system/syscall_linux_64.go
vendor/github.com/opencontainers/runc/vendor.conf

backports of:
- https://github.com/moby/moby/pull/39995 Update containerd to v1.2.10
- https://github.com/moby/moby/pull/40001 Update runc to v1.0.0-rc8-92-g84373aaa (CVE-2019-16884)
>The tenth patch release for containerd 1.2 includes only one main bug fix in the
CRI plugin, but includes updated vendors/build runtimes that fix 2 reported CVEs in
runc and the Golang 1.12 runtime respectively.
>## Notable Updates
>* Update the runc vendor to capture the fix for CVE-2019-16884. Fixed by PR #3685
>    - More details on the runc CVE in opencontainers/runc#2128, fixed by opencontainers/runc#2129
>* Update Golang runtime to 1.12.10 to handle CVE-2019-16276. More detail on the Golang CVE available in golang/go#34540
>* CRI fixes:
>    - Fix a bug that the default UNIX path is not in the default …

[19.03 backport] update containerd 1.2.10, runc v1.0.0-rc8-92-g84373aaa (CVE-2019-16884)

---

hack/dockerfile/install/containerd.installer
hack/dockerfile/install/runc.installer

backports of:
- https://github.com/moby/moby/pull/39995 Update containerd to v1.2.10
- https://github.com/moby/moby/pull/40001 Update runc to v1.0.0-rc8-92-g84373aaa (CVE-2019-16884)
- **only the first commit**
closes https://github.com/docker/engine/pull/283 [18.09 backport] Update containerd to v1.2.8
closes https://github.com/docker/engine/pull/367 [18.09 backport] Update containerd to v1.2.9
>The tenth patch release for containerd 1.2 includes only one main bug fix in the
CRI plugin, but includes updated vendors/build runtimes that fix 2 reported CVEs in
runc and the Golang 1.12 runtime respectively.
>## Notable Updates
>* Update the runc vendor to capture the fix for CVE-2019-16884. Fixed by PR #3685
>    - More details on the runc CVE in opencontainers/runc#2128, fixed by …

[18.09 backport] update containerd 1.2.10, runc v1.0.0-rc8-92-g84373aaa (CVE-2019-16884)

---

hack/dockerfile/install/containerd.installer

backport of 
- https://github.com/moby/moby/pull/39874 Update containerd to v1.2.9
Update containerd to v1.2.9. https://github.com/containerd/containerd/releases/tag/v1.2.9 
> The ninth patch release for containerd 1.2 provides a handful of bug fixes and an
update to the gRPC vendored codebase to include 3 CVE fixes provided in the upstream
v1.23.0 release of gRPC. Note that updating gRPC to the current release required small
changes to our core containerd codebase to match the upstream changes since gRPC v1.12.0.
These changes have been backported from containerd's master branch, as well as a
similar small change in ttrpc, requiring that package's vendoring to be updated.
> In addition to the gRPC update to include CVE fixes, fixes were made to correct a
container's default Unix …

[18.09 backport] Update containerd to v1.2.9

---

hack/dockerfile/install/containerd.installer

backport of https://github.com/moby/moby/pull/39364 and https://github.com/moby/moby/pull/39786 for 18.09
From the release notes: https://github.com/containerd/containerd/releases/tag/v1.2.7
> Welcome to the v1.2.7 release of containerd!
>
> The seventh patch release for containerd 1.2 introduces OCI image
> descriptor annotation support and contains fixes for containerd shim logs,
> container stop/deletion, cri plugin and selinux.
>
> It also contains several important bug fixes for goroutine and file
> descriptor leakage in containerd and containerd shims.
>
> Notable Updates
>
> - Support annotations in the OCI image descriptor, and filtering image by annotations. containerd/containerd#3254
> - Support context timeout in ttrpc which can help avoid containerd hangs when a shim is …

[18.09 backport] Update containerd to v1.2.8

---

Dockerfile
Dockerfile.e2e
Dockerfile.simple
Dockerfile.windows

full diff: https://github.com/golang/go/compare/go1.12.9...go1.12.10
```
Hi gophers,
We have just released Go 1.13.1 and Go 1.12.10 to address a recently reported security issue. We recommend that all affected users update to one of these releases (if you're not sure which, choose Go 1.13.1).
net/http (through net/textproto) used to accept and normalize invalid HTTP/1.1 headers with a space before the colon, in violation of RFC 7230. If a Go server is used behind an uncommon reverse proxy that accepts and forwards but doesn't normalize such invalid headers, the reverse proxy and the server can interpret the headers differently. This can lead to filter bypasses or request smuggling, the latter if requests from separate clients are multiplexed onto the same upstream connection by the proxy. …
```

[19.03] bump golang 1.12.10 (CVE-2019-16276)

---

Dockerfile
Dockerfile.e2e
Dockerfile.simple
Dockerfile.windows

Since golang 1.11 is no longer maintained and in view of [recent golang security update](https://groups.google.com/forum/#!msg/golang-announce/cszieYyuL9Q/g4Z7pKaqAgAJ), let's jump straight to 1.12.10.

[18.09] bump golang 1.12.10 (CVE-2019-16276)

---

integration-cli/check_test.go

backport of https://github.com/moby/moby/pull/40016
fixes https://github.com/moby/moby/issues/40010
noticed this in https://github.com/moby/moby/issues/40010, where it was reported that (e.g.) `TestDockerNetworkSuite/TestExternalVolumeDriverBindExternalVolume` was failing, but that test should not be part of `TestDockerNetworkSuite`. Then I noticed that the actual network tests (e.g. `TestDockerNetworkLsDefault`) were not running 🙀 😅

[19.03 backport] integration-cli: fix DockerNetworkSuite not being run

---

hack/make/test-docker-py

clean cherry-pick of 48353e1 from https://github.com/moby/moby/pull/40030
```
$ git cherry-pick -s -x 48353e16fe4bc06764ceb6bced0fbe832803ede4
[bump_docker_py ec0e20a9eb] Temporarily switch docker-py to "master"
Author: Sebastiaan van Stijn <github@gone.nl>
Date: Wed Oct 2 17:54:48 2019 +0200
1 file changed, 1 insertion(+), 1 deletion(-)
```

[19.03 backport] Temporarily switch docker-py to "master"

---

hack/make/test-docker-py

backport of https://github.com/moby/moby/pull/40030
The docker-py tests were broken, because the version of py-test that was used, used a dependency that had a new major release with a breaking change.
Unfortunately, it was not pinned to a specific version, so when the dependency did the release, py-test broke;
```
22:16:47  Traceback (most recent call last):
22:16:47    File "/usr/local/bin/pytest", line 10, in <module>
22:16:47      sys.exit(main())
22:16:47    File "/usr/local/lib/python3.6/site-packages/_pytest/config/__init__.py", line 61, in main
22:16:47      config = _prepareconfig(args, plugins)
22:16:47    File "/usr/local/lib/python3.6/site-packages/_pytest/config/__init__.py", line 182, in _prepareconfig
22:16:47      config = get_config()
22:16:47    File …
```

[18.09 backport] Temporarily switch docker-py to "master"

---

api/swagger.yaml
docs/api/version-history.md

backport of https://github.com/moby/moby/pull/40028
The /session endpoint left experimental in API V1.39 / Docker 18.09 through 239047c2d36706f2826b0a9bc115e0a08b1c3d27 and 01c9e7082eba71cbe60ce2e47acb9aad2c83c7ef (https://github.com/moby/moby/pull/37686), but the API reference was not updated accordingly.
This updates the API documentation to match the change.
```Markdown
* API: update docs that `/session` endpoint left experimental in V1.39 [moby/moby#40028](https://github.com/moby/moby/pull/40028)
```

[19.03 backport] API: update docs that /session left experimental in V1.39

---

api/swagger.yaml
docs/api/version-history.md

backport of https://github.com/moby/moby/pull/40028
The /session endpoint left experimental in API V1.39 / Docker 18.09 through 239047c2d36706f2826b0a9bc115e0a08b1c3d27 and 01c9e7082eba71cbe60ce2e47acb9aad2c83c7ef (https://github.com/moby/moby/pull/37686), but the API reference was not updated accordingly.
This updates the API documentation to match the change.
```Markdown
* API: update docs that `/session` endpoint left experimental in V1.39 [moby/moby#40028](https://github.com/moby/moby/pull/40028)
```

[18.09 backport] API: update docs that /session left experimental in V1.39

---

hack/dockerfile/install/proxy.installer
vendor.conf
vendor/github.com/docker/libnetwork/drivers/bridge/setup_ip_forwarding.go

this rolls back the libnetwork bump from https://github.com/docker/engine/commit/559be42fc26048f4069de64f84202803a113413a with 1 commit
The patch made in  docker/libnetwork#2450 caused a breaking change in the
networking behaviour, causing Kubernetes installations on Docker Desktop
(and possibly other setups) to fail.
Rolling back this change in the 19.03 branch while we investigate if there
are alternatives.
diff: https://github.com/docker/libnetwork/compare/45c710223c5fbf04dc3028b9a90b51892e36ca7f...96bcc0dae898308ed659c5095526788a602f4726

[19.03] roll-back libnetwork iptables forward policy change [DESKTOP-1934]

---

Jenkinsfile

backports of:
- https://github.com/moby/moby/pull/39932 Jenkinsfile: remove redundant -f Dockerfile
- https://github.com/moby/moby/pull/40035 Jenkinsfile: set repo and branch, to assist validate_diff()

[19.03 backport] Jenkinsfile: set repo and branch, to assist validate_diff()

---

hack/dockerfile/install/proxy.installer
vendor.conf
vendor/github.com/docker/libnetwork/firewall_linux.go

This change caused a regression, causing the DOCKER-USER chain
to not be created, despite iptables being enabled on the daemon.
- updates lib network to the latest bump_19.03 branch
- brings in https://github.com/docker/libnetwork/pull/2470 [19.03] revert controller: Check if IPTables is enabled for arrangeUserFilterRule ENGCORE-1114
- reverts https://github.com/docker/libnetwork/pull/2339 controller: Check if IPTables is enabled for arrangeUserFilterRule
- fixes [ENGCORE-1114]
- fixes https://github.com/docker/for-linux/issues/810 DOCKER-USER iptables chain missing in 19.03.3
[ENGCORE-1114]: https://docker.atlassian.net/browse/ENGCORE-1114

[19.03 backport] revert controller: Check if IPTables is enabled for arrangeUserFilterRule ENGCORE-1114

---

Jenkinsfile

backport of https://github.com/moby/moby/pull/40119
Commit 7019b60d0d6f3d69e6ccf481ca0a912905a9c1d (https://github.com/moby/moby/pull/40035) added these
env-vars to other stages, but forgot to update the DCO stage,
which also does a diff to validate commits that are in a PR.
this should fix the issue we're seeing in https://github.com/docker/engine/pull/408#issuecomment-544376931

[19.03 backport] Jenkinsfile: set repo and branch for DCO check as well

---

integration-cli/docker_api_images_test.go

backport of https://github.com/moby/moby/pull/39910
addresses https://github.com/moby/moby/issues/39909
I've seen this test fail a number of times recently on RS1
Looking at failures, the test is taking a long time ro run (491.77s, which is
more than 8 minutes), so perhaps it's just too slow on RS1, which may be
because we switch to a different base image, or because we're now running
on different machines.
Compared to RS5 (still slow, but a lot faster);
```
--- PASS: Test/DockerSuite/TestAPIImagesSaveAndLoad (146.25s)
```
```
--- FAIL: Test/DockerSuite/TestAPIImagesSaveAndLoad (491.77s)
cli.go:45: assertion failed:
Command:  d:\CI-5\CI-93d2cf881\binary\docker.exe inspect --format {{.Id}} sha256:69e7c1ff23be5648c494294a3808c0ea3f78616fad67bfe3b10d3a7e2be5ff02
ExitCode: 1
Error:    exit …
```

[18.09 backport] integration-cli: Skip TestAPIImagesSaveAndLoad on RS3 and older

---

integration-cli/docker_api_swarm_test.go
integration-cli/docker_cli_swarm_test.go
internal/test/daemon/node.go
vendor.conf
vendor/github.com/docker/swarmkit/agent/agent.go
vendor/github.com/docker/swarmkit/agent/session.go
vendor/github.com/docker/swarmkit/agent/worker.go
vendor/github.com/docker/swarmkit/api/dispatcher.pb.go
vendor/github.com/docker/swarmkit/api/logbroker.pb.go
vendor/github.com/docker/swarmkit/api/raft.pb.go
vendor/github.com/docker/swarmkit/api/types.pb.go
vendor/github.com/docker/swarmkit/manager/dispatcher/dispatcher.go
vendor/github.com/docker/swarmkit/manager/drivers/provider.go
vendor/github.com/docker/swarmkit/manager/manager.go
vendor/github.com/docker/swarmkit/manager/orchestrator/restart/restart.go
vendor/github.com/docker/swarmkit/manager/orchestrator/service.go
vendor/github.com/docker/swarmkit/manager/orchestrator/update/updater.go
vendor/github.com/docker/swarmkit/manager/scheduler/nodeinfo.go
vendor/github.com/docker/swarmkit/node/node.go

- _Partial_ backport of https://github.com/moby/moby/pull/39531 integration-cli: fix swarm tests flakiness
- **skipped second commit (SwarmKit bump) as that requires backport to the SwarmKit bump_v18.09 branch**
- addresses https://github.com/moby/moby/issues/36903 Flaky test: TestAPISwarmServicesCreate
- addresses https://github.com/moby/moby/issues/34988 Flaky test: TestAPISwarmRaftQuorum
- addresses https://github.com/moby/moby/issues/37132 Flaky test: TestServicePlugin, TestCreateServiceSecretFileMode
- addresses https://github.com/moby/moby/issues/32673 Flaky test: TestAPISwarmLeaderElection
- addresses https://github.com/moby/moby/issues/28240 Flaky test: DockerSwarmSuite.TestSwarmRotateUnlockKey
- addresses https://github.com/moby/moby/issues/38885 Flaky test: …

[18.09 backport] integration-cli: fix swarm tests flakiness

---

daemon/monitor.go

backport of https://github.com/moby/moby/pull/39497
Before this change we just accept that any error is "not found" and it
could be something else, but even if it it is just a "not found" kind of
error this should be dealt with from the container store and not the
event processor.

[18.09 backport] Propagate GetContainer error from event processor

---

api/types/filters/parse.go
api/types/filters/parse_test.go
builder/builder-next/builder.go
builder/builder-next/controller.go
daemon/config/builder.go
daemon/config/builder_test.go

backport of 
- https://github.com/moby/moby/pull/38239 filters: add Clone() method
- used in testing
- https://github.com/moby/moby/pull/39029 Remove deprecated filter functions
- to get a clean cherry-pick; only removes some dead code
- https://github.com/moby/moby/pull/39979 daemon/config: fix filter type in BuildKit GC config
- fixes https://github.com/moby/moby/issues/39601 "Example Buildkit GC configuration results in daemon error"
- https://github.com/moby/moby/pull/40118 Add GoDoc to fix linting validation

[18.09 backport] daemon/config: fix filter type in BuildKit GC config

---

contrib/dockerd-rootless.sh
hack/dockerfile/install/rootlesskit.installer

backport of https://github.com/moby/moby/pull/39840
When slirp4netns v0.4.0+ is used, now slirp4netns is hardened using
mount namespace ("sandbox") and seccomp to mitigate potential
vulnerabilities.
bump up rootlesskit: https://github.com/rootless-containers/rootlesskit/compare/2fcff6ceae968a1d895e6205e5154b107247356f...791ac8cb209a107505cd1ca5ddf23a49913e176c
```Markdown
* Update to RootlessKit to v0.7.0 to harden slirp4netns with mount namespace and seccomp
```

[19.03 backport] rootless: harden slirp4netns with mount namespace and seccomp

---

daemon/monitor.go

backport of https://github.com/moby/moby/pull/39497
Before this change we just accept that any error is "not found" and it
could be something else, but even if it it is just a "not found" kind of
error this should be dealt with from the container store and not the
event processor.

[19.03 backport] Propagate GetContainer error from event processor

---

api/types/filters/parse.go
builder/builder-next/controller.go
daemon/config/builder.go
daemon/config/builder_test.go

backport of 
- https://github.com/moby/moby/pull/39979 daemon/config: fix filter type in BuildKit GC config
- fixes https://github.com/moby/moby/issues/39601 "Example Buildkit GC configuration results in daemon error"
- https://github.com/moby/moby/pull/40118 Add GoDoc to fix linting validation

[19.03 backport] daemon/config: fix filter type in BuildKit GC config

---

builder/builder-next/controller.go
daemon/config/builder.go

backport of https://github.com/moby/moby/pull/39144
relates to:
- https://github.com/moby/buildkit/issues/950 Implement entitlement security.unconfined
- https://github.com/moby/buildkit/pull/1081 Implement frontend support for RUN --security=insecure
buildkit supports entitlements like network-host and security-insecure.
this patch aims to make it configurable through daemon.json file.
by default network-host is enabled & security-insecure is disabled.
option to enable/disable buildkit's entitlements settings for moby
fixes part of issue discussed here https://github.com/moby/buildkit/issues/950#issuecomment-484790342
Added `entitlements` in builder config
**- A picture of a cute animal (not mandatory but …

[19.03 backport] builder entitlements configuration added.

---

vendor.conf
vendor/github.com/moby/buildkit/frontend/dockerfile/dockerfile2llb/convert.go
vendor/github.com/moby/buildkit/session/sshforward/ssh.go
vendor/github.com/moby/buildkit/solver/llbsolver/ops/exec.go

https://github.com/moby/buildkit/pull/1243
changelog line:
```
- Fix builder-next: permission errors on using build secrets or ssh forwarding with userns-remap.
- Fix builder-next: copying a symlink inside an already copied directory.
```

[19.03] vendor: update buildkit to ff93519ee

---

integration/network/service_test.go
vendor.conf
vendor/github.com/docker/swarmkit/manager/manager.go

depends on:
closes https://github.com/docker/engine/pull/375 (which is an alternative for this one)
brings back https://github.com/docker/engine/pull/369
full diff: https://github.com/docker/swarmkit/compare/bbe341867eae1615faf8a702ec05bfe986e73e06...f35d9100f2c6ac810cc8d7de6e8f93dcc7a42d29
- docker/swarmkit#2891 [19.03 backport] Remove hardcoded IPAM config subnet value for ingress network
- backport of docker/swarmkit#2890 Remove hardcoded IPAM config subnet value for ingress network
- fixes [ENGCORE-1028] Specifying --default-addr-pool for docker swarm init is not picked up by ingress network
[ENGCORE-1028]: https://docker.atlassian.net/browse/ENGCORE-1028
To fix CI being red after merging https://github.com/docker/engine/pull/369 (effectively a backport of …

[19.03 backport] Add TC to check dynamic subnet for ingress network

---

vendor.conf
vendor/github.com/moby/buildkit/cache/refs.go

Brings in:
https://github.com/moby/buildkit/pull/1257 cache: fix possible concurrent maps write on parent release

[19.03] vendor: update buildkit to 928f3b48

---

daemon/daemon_unix.go
daemon/graphdriver/copy/copy.go
daemon/graphdriver/devmapper/deviceset.go
pkg/loopback/loopback.go
pkg/system/stat_linux.go

(cherry picked from commit 5f0231bca193320e1a3d785a3ade0e64241fe580)
Signed-off-by: Dominic Yin <yindongchao@inspur.com>
backport of https://github.com/moby/moby/pull/39646
fixed compiling errors on mips architecture
This PR fixed build errors about like "cannot use s.Rdev (type uint32) as type uint64" when targeting mips due to the Dev and Rdev in Stat_t being 32-bit on 32-bit mips.
Inserted casts to uint64 where needed.
Note that we cannot build docker on mips64le in conventional way, instead we have to run the script directly. After fix some other problems like ztypes and zerrors in golang.org/x/sys, we build docker successfully following these short steps below:
```
git clone -b v18.09.8-ce https://github.com/docker/docker-ce …
```

[19.03 backport] cast Dev and Rdev of Stat_t to uint64 for mips

---

hack/make/test-docker-py

backport of https://github.com/moby/moby/pull/40343
https://github.com/docker/docker-py/pull/2369, https://github.com/docker/docker-py/pull/2380, and https://github.com/docker/docker-py/pull/2382 are included in docker-py v4.1.0, so we can re-enable these tests
The ImageCollectionTest.test_pull_multiple test performs a `docker pull` without
a `:tag` specified) to pull all tags of the given repository (image).
After pulling the image, the image(s) pulled are checked to verify if the list
of images contains the `:latest` tag.
However, the test assumes that all tags of the image are tags for the same
version of the image (same digest), and thus a *single* image is returned, which
is not always the case.
Currently, the `hello-world:latest` and `hello-world:linux` tags point to a
different …

[19.03 backport] docker-py: skip broken ImageCollectionTest::test_pull_multiple, and re-enable fixed tests

---

hack/dockerfile/install/containerd.installer
hack/dockerfile/install/runc.installer

full diff: https://github.com/opencontainers/runc/compare/3e425f80a8c931f88e6d94a8c831b9d5aa481657...v1.0.0-rc9
- opencontainers/runc#1951 Add SCMP_ACT_LOG as a valid Seccomp action
- opencontainers/runc#2130 *: verify operations on /proc/... are on procfs
This is an additional mitigation for CVE-2019-16884. The primary problem
is that Docker can be coerced into bind-mounting a file system on top of
/proc (resulting in label-related writes to /proc no longer happening).
While we are working on mitigations against permitting the mounts, this
helps avoid our code from being tricked into writing to non-procfs
files. This is not a perfect solution (after all, there might be a
bind-mount of a different procfs file over the target) but in order to
exploit that you would need to be able to tweak …

[19.03] Update containerd to v1.2.11, runc v1.0.0-rc9

---

Dockerfile
Dockerfile.e2e
Dockerfile.simple
Dockerfile.windows

Update Golang 1.12.14
------------------------
go1.12.14 (released 2019/12/04) includes a fix to the runtime. See the Go 1.12.14
milestone on our issue tracker for details:
https://github.com/golang/go/issues?q=milestone%3AGo1.12.14+label%3ACherryPickApproved
Update Golang 1.12.13
------------------------
go1.12.13 (released 2019/10/31) fixes an issue on macOS 10.15 Catalina where the
non-notarized installer and binaries were being rejected by Gatekeeper. Only macOS
users who hit this issue need to update.

[19.03] Bump Golang 1.12.14

---

hack/make/.go-autogen

When trying to build with some pretty typical version strings this was
causing failures trying to generate the windows resource file.
The resource file is already gated by an `ifdef` for this var, so
instead of blindly setting based on "VERSION", which can contain some
characters which are incompatible (e.g. 1.2.3.rc.0 will fail due to the
".rc").
Signed-off-by: Brian Goff <cpuguy83@gmail.com>
(cherry picked from commit ce931f28ea8768baa7ca2725d9030fbf8a40d3ba)
Signed-off-by: Brian Goff <cpuguy83@gmail.com>
Backports moby/moby#40169

[19.03] Windows: Only set VERSION_QUAD if unset

---

daemon/logger/gelf/gelf.go

backport of https://github.com/moby/moby/pull/40234 for 19.03
The [gelf payload specification](http://docs.graylog.org/en/2.4/pages/gelf.html#gelf-payload-specification) demands that the field `short_message` *MUST* be set by the client library.
Since docker logging via the gelf driver sends messages line by line, it can happen that messages with an empty `short_message` are passed on. This causes strict downstream processors (like graylog) to raise an exception.
The logger now replaces message lines of length zero with the content `<empty-line>`. This is done
for the following reasons:
- Keeps it possible to reconstruct the logging output in its entirety
- Does not break logging setups that need the information from empty logs (e.g. Logstash rules)
fixes …

[19.03 backport] logger/gelf: Skip empty lines to comply with spec

---

daemon/daemon_windows.go

backport of https://github.com/moby/moby/pull/39733
#38301 did set container restart/restore task parallelism limit to 128*NumCPU which is good limit for Linux containers. Especially when they are made correctly by following one process per container rule.
However Windows containers are much heavier and example Windows Server 2019 base image `mcr.microsoft.com/windows/servercore:ltsc2019` it selves includes ~20 system processes which causes restoring to generate so high load to server and it cannot response anything else until restore is completed.
Disabled restore parallelism from Windows platform.
I created 100 containers with restart policy:
```powershell
for($i=1;$i -le 100;$i++) {
docker run -d --restart always --network nat …
```

[19.03 backport] Windows: Use system specific parallelism value on containers restart

---

builder/builder-next/executor_unix.go
daemon/oci_linux.go
hack/dockerfile/install/proxy.installer
vendor.conf
vendor/github.com/docker/libnetwork/agent.go
vendor/github.com/docker/libnetwork/drivers/overlay/overlay.go
vendor/github.com/docker/libnetwork/sandbox_externalkey_unix.go

backport of:
- https://github.com/moby/moby/pull/39822 daemon: Use short libnetwork ID in exec-root
- https://github.com/docker/libnetwork/pull/2482 [19.03 backport] Shorten controller ID in exec-root to not hit UNIX_PATH_MAX
- backports https://github.com/docker/libnetwork/pull/2443 Shorten controller ID in exec-root to not hit UNIX_PATH_MAX
- https://github.com/docker/libnetwork/pull/2483 [19.03 backport] Fix panic in drivers/overlay/encryption.go
- backports: https://github.com/docker/libnetwork/pull/2462 Fix panic in drivers/overlay/encryption.go
Relates to / addresses: https://github.com/moby/moby/issues/39608 Upgrade to 19.03 from 18 results in libnetwork-setkey hitting UNIX_PATH_MAX limit

[19.03 backport] daemon: Use short libnetwork ID in exec-root & update libnetwork

---

hack/dockerfile/install/rootlesskit.installer

backport https://github.com/moby/moby/pull/40317

[19.03 backport] rootless: fix proxying UDP packets

---

Dockerfile
Dockerfile.e2e
Dockerfile.simple
Dockerfile.windows

full diff: https://github.com/golang/go/compare/go1.12.14...go1.12.15
go1.12.15 (released 2020/01/09) includes fixes to the runtime and the net/http
package. See the Go 1.12.15 milestone on the issue tracker for details:
https://github.com/golang/go/issues?q=milestone%3AGo1.12.15+label%3ACherryPickApproved

[19.03] Bump Golang 1.12.15

---

hack/make/test-docker-py

backport of https://github.com/moby/moby/pull/40034
relates to https://github.com/docker/engine/pull/437

[19.03 backport] bump docker-py to 4.1.0

---

pkg/parsers/kernel/kernel_windows.go

backport of https://github.com/moby/moby/pull/39883
relates to https://github.com/moby/moby/pull/39549

[19.03 backport] pkg/parsers/kernel: gofmt hex value (preparation for Go 1.13+)

---

pkg/namesgenerator/names-generator.go

Could be misinterpreted as something not too kosher
backport of https://github.com/moby/moby/pull/39455
fixes https://github.com/moby/moby/issues/39451 Unfortunate name combo

[19.03 backport] Remove cocky from names-generator

---

Dockerfile.windows
docs/contributing/software-req-win.md
hack/ci/windows.ps1

backport of https://github.com/moby/moby/pull/39888
Unlike Linux which uses a temp dir as GOPATH, Windows
uses c:\go. Among other things, this blocks go get.
Moving GOPATH to c:\gopath and updating references in
comments and documentation.
Currently the change is being scoped narrowly. In the
future GOPATH value could be passed as a parameter to
the ps1 scripts.

[19.03 backport] Move GOPATH out from under the GO source tree

---

container/container_unix.go

backport of https://github.com/moby/moby/pull/39653
Addresses https://github.com/moby/moby/issues/16902#issuecomment-517576013
When cleaning up IPC mounts, the daemon could log a warning if the IPC mount was not found;
```
cleanup: failed to unmount IPC: umount /var/lib/docker/containers/90f408e26e205d30676655a08504dddc0d17f5713c1dd4654cf67ded7d3bbb63/mounts/shm, flags: 0x2: no such file or directory"
```
These warnings are safe to ignore, but can cause some confusion;  `container.UnmountIpcMount()`
already attempted to suppress these warnings, however, `mount.Unmount()` returns a `mountError`,
which nests the original error, therefore detecting failed.
This parch uses `errors.Cause()` to get the _underlying_ error to detect if it's a "is not exist". …

[19.03 backport] Fix "no such file or directory" warning when unmounting IPC mount

---

errdefs/http_helpers.go

backport of https://github.com/moby/moby/pull/39526
The `statusCodeFromGRPCError` and `statusCodeFromDistributionError`
helpers are used by `GetHTTPErrorStatusCode`, which already recurses
if the error implements the `Causer` interface.

[19.03 backport] errdefs: remove unneeded recursive calls

---

hack/dockerfile/install/proxy.installer
vendor.conf
vendor/github.com/docker/libnetwork/drivers/bridge/setup_device.go

full diff: https://github.com/docker/libnetwork/compare/d9a6682a4dbb13b1f0d8216c425fe9ae010a0f23...9fd385be8302dbe1071a3ce124891893ff27f90f
- https://github.com/docker/libnetwork/pull/2495 [19.03 backport] bridge: Fix hwaddr set race between us and udev
- backport of https://github.com/docker/libnetwork/pull/2380

[19.03] Bump 19.03 libnetwork refpoint

---

cmd/dockerd/daemon.go

backport of https://github.com/moby/moby/pull/39514
see https://github.com/moby/moby/pull/39454#issuecomment-511054056
Before this change:
dockerd -H unix:///run/docker.sock -H unix:///run/docker.sock -H unix:///run/docker.sock
...
INFO[2019-07-13T00:02:36.195090937Z] Daemon has completed initialization
INFO[2019-07-13T00:02:36.215940441Z] API listen on /run/docker.sock
INFO[2019-07-13T00:02:36.215933172Z] API listen on /run/docker.sock
INFO[2019-07-13T00:02:36.215990566Z] API listen on /run/docker.sock
After this change:
dockerd -H unix:///run/docker.sock -H unix:///run/docker.sock -H unix:///run/docker.sock
...
INFO[2019-07-13T00:01:37.533579874Z] Daemon has completed initialization
INFO[2019-07-13T00:01:37.567045771Z] API listen on /run/docker.sock …

[19.03 backport] daemon: don't listen on the same address multiple times

---

container/health.go

backport of https://github.com/moby/moby/pull/39645
Fixes https://github.com/moby/moby/issues/39503
Use a local variable `status` instead of `s.Health.Status` as the return variable of function `(Health).String`, in order to avoid potential data race.
Besides potential data race, I think the old code has another problem: if `s.Health.Status` is "", then the old `(Health).String` will return "", but this is inconsistent with `(Health).Status`, which will return `types.Unhealthy`. After my commit, the return value of `(Health).String` will be consistent with `(Health).Status`.
All read/write operations to `s.Health.Status` is protected by `s.mu.Lock()`, except this one in `(Health).String`. So I suppose this read operation without critical section …

[19.03 backport] Avoid a data race in container/health.go

---

daemon/images/image_builder.go

backport of https://github.com/moby/moby/pull/39217 for 19.03

[19.03 backport] LCOW: Fix FROM scratch

---

pkg/system/xattrs_linux.go

If `unix.Lgetxattr` returns an error, then `sz == -1` which will cause a
runtime panic if `errno == unix.ERANGE`.
backport of https://github.com/moby/moby/pull/40283

[19.03 backport] Fix possible runtime panic in Lgetxattr
